<?php
/**
 * Bender Modeler
 *
 * Our Simple Models
 *
 * @category   lib
 * @package    lib_models
 * @copyright  Copyright (c) 2008-2010 Bender Modeler (http://www.ctrl-zetta.com/#code)
 * @author     <zetta> <chentepixtol>, $LastChangedBy$
 * @version    1.0.0 SVN: $Id$
 */
/**
 * Dependences
 */
require_once "application/models/beans/AccessRole.php";

/**
 * Clase AccessRoleFactory
 *
 * @category   lib
 * @package    lib_models
 * @subpackage lib_models_factories
 * @copyright  Copyright (c) 2008-2010 Bender Modeler (http://www.ctrl-zetta.com/#code) 
 * @copyright  This File as been proudly generated by Bender (http://code.google.com/p/bender-modeler/). <chentepixtol> <zetta>
 * @author     <zetta> & <chentepixtol>
 * @version    1.0.0 SVN: $Revision$
 */
class AccessRoleFactory
{

   /**
    * Create a new AccessRole instance
    * @param string $name
    * @param int $status
    * @return AccessRole
    */
   public static function create($name, $status)
   {
      $newAccessRole = new AccessRole();
      $newAccessRole->setName($name);
      $newAccessRole->setStatus($status);
      return $newAccessRole;
   }
   
    /**
     * Método que construye un objeto AccessRole y lo rellena con la información del rowset
     * @param array $fields El arreglo que devolvió el objeto Zend_Db despues del fetch
     * @return AccessRole 
     */
    public static function createFromArray($fields)
    {
        $newAccessRole = new AccessRole();
        $newAccessRole->setIdAccessRole($fields['id_access_role']);
        $newAccessRole->setName($fields['name']);
        $newAccessRole->setStatus($fields['status']);
        return $newAccessRole;
    }
   
}
