<?php
/**
 * SRP
 *
 * SRP INELECTRA
 *
 * @category   lib
 * @package    lib_models
 * @copyright  Copyright (c) 2010 PCSMEXICO
 * @author     <arturo>, $LastChangedBy$
 * @version    1.0.2 SVN: $Id$
 */
/**
 * Dependences
 */
require_once "application/models/beans/DepartmentProjectTask.php";

/**
 * Clase DepartmentProjectTaskFactory
 *
 * @category   lib
 * @package    lib_models
 * @subpackage lib_models_factories
 * @copyright  Copyright (c) 2010 PCSMEXICO 
 * @copyright  This File has been proudly generated by Bender (http://code.google.com/p/bender-modeler/). <chentepixtol> <zetta>
 * @author     <zetta> & <chentepixtol>
 * @version    1.0.2 SVN: $Revision$
 */
class DepartmentProjectTaskFactory
{

   /**
    * Create a new DepartmentProjectTask instance
    * @param string $taskCode
    * @param string $taskName
    * @param int $type
    * @param int $status
    * @return DepartmentProjectTask
    */
   public static function create($taskCode, $description, $type, $status)
   {
      //throw new Exception('Factory Deprecated');
      $newDepartmentProjectTask = new DepartmentProjectTask();
      $newDepartmentProjectTask
          ->setTaskCode($taskCode)
          ->setDescription($description)
          ->setType($type)
          ->setStatus($status)
      ;
      return $newDepartmentProjectTask;
   }
   
    /**
     * Método que construye un objeto DepartmentProjectTask y lo rellena con la información del rowset
     * @param array $fields El arreglo que devolvió el objeto Zend_Db despues del fetch
     * @return DepartmentProjectTask 
     */
    public static function createFromArray($fields)
    {
        $newDepartmentProjectTask = new DepartmentProjectTask();
        $newDepartmentProjectTask->setIdDepartmentProjectTask($fields['id_department_project_task']);
        $newDepartmentProjectTask->setIdProjectTask($fields['id_project_task']);
        $newDepartmentProjectTask->setTaskCode($fields['task_code']);
        $newDepartmentProjectTask->setDescription($fields['description']);
        $newDepartmentProjectTask->setType($fields['type']);
        $newDepartmentProjectTask->setStatus($fields['status']);
        return $newDepartmentProjectTask;
    }
   
}
