<?php
/**
 * SRP
 *
 * SRP INELECTRA
 *
 * @category   lib
 * @package    lib_models
 * @copyright  Copyright (c) 2010 PCSMEXICO
 * @author     <arturo>, $LastChangedBy$
 * @version    1.0.2 SVN: $Id$
 */
/**
 * Dependences
 */
require_once "application/models/beans/Email.php";

/**
 * Clase EmailFactory
 *
 * @category   lib
 * @package    lib_models
 * @subpackage lib_models_factories
 * @copyright  Copyright (c) 2010 PCSMEXICO 
 * @copyright  This File has been proudly generated by Bender (http://code.google.com/p/bender-modeler/). <chentepixtol> <zetta>
 * @author     <zetta> & <chentepixtol>
 * @version    1.0.2 SVN: $Revision$
 */
class EmailFactory
{

   /**
    * Create a new Email instance
    * @param int $idPerson
    * @param string $email
    * @param int $type
    * @return Email
    */
   public static function create($idPerson, $email, $type)
   {
      //throw new Exception('Factory Deprecated');
      $newEmail = new Email();
      $newEmail
          ->setIdPerson($idPerson)
          ->setEmail($email)
          ->setType($type)
      ;
      return $newEmail;
   }
   
    /**
     * Método que construye un objeto Email y lo rellena con la información del rowset
     * @param array $fields El arreglo que devolvió el objeto Zend_Db despues del fetch
     * @return Email 
     */
    public static function createFromArray($fields)
    {
        $newEmail = new Email();
        $newEmail->setIdEmail($fields['id_email']);
        $newEmail->setIdPerson($fields['id_person']);
        $newEmail->setEmail($fields['email']);
        $newEmail->setType($fields['type']);
        return $newEmail;
    }
   
}
