<?php
/**
 * Bender Modeler
 *
 * Our Simple Models
 *
 * @category   lib
 * @package    lib_models
 * @copyright  Copyright (c) 2008-2010 Bender Modeler (http://www.ctrl-zetta.com/#code)
 * @author     <zetta> <chentepixtol>, $LastChangedBy$
 * @version    1.0.0 SVN: $Id$
 */
/**
 * Dependences
 */
require_once "application/models/beans/SecurityController.php";

/**
 * Clase SecurityControllerFactory
 *
 * @category   lib
 * @package    lib_models
 * @subpackage lib_models_factories
 * @copyright  Copyright (c) 2008-2010 Bender Modeler (http://www.ctrl-zetta.com/#code) 
 * @copyright  This File as been proudly generated by Bender (http://code.google.com/p/bender-modeler/). <chentepixtol> <zetta>
 * @author     <zetta> & <chentepixtol>
 * @version    1.0.0 SVN: $Revision$
 */
class SecurityControllerFactory
{

   /**
    * Create a new SecurityController instance
    * @param string $name
    * @return SecurityController
    */
   public static function create($name)
   {
      $newSecurityController = new SecurityController();
      $newSecurityController->setName($name);
      return $newSecurityController;
   }
   
    /**
     * Método que construye un objeto SecurityController y lo rellena con la información del rowset
     * @param array $fields El arreglo que devolvió el objeto Zend_Db despues del fetch
     * @return SecurityController 
     */
    public static function createFromArray($fields)
    {
        $newSecurityController = new SecurityController();
        $newSecurityController->setIdController($fields['id_controller']);
        $newSecurityController->setName($fields['name']);
        return $newSecurityController;
    }
   
}
