<?php
/**
 * SRP
 *
 * SRP INELECTRA
 *
 * @category   lib
 * @package    lib_models
 * @copyright  Copyright (c) 2010 PCSMEXICO
 * @author     <arturo>, $LastChangedBy$
 * @version    1.0.2 SVN: $Id$
 */
/**
 * Dependences
 */
require_once "application/models/beans/User.php";

/**
 * Clase UserFactory
 *
 * @category   lib
 * @package    lib_models
 * @subpackage lib_models_factories
 * @copyright  Copyright (c) 2010 PCSMEXICO 
 * @copyright  This File has been proudly generated by Bender (http://code.google.com/p/bender-modeler/). <chentepixtol> <zetta>
 * @author     <zetta> & <chentepixtol>
 * @version    1.0.2 SVN: $Revision$
 */
class UserFactory
{

   /**
    * Create a new User instance
    * @param string $username
    * @param string $password
    * @param int $status
    * @param int $idAccessRole
    * @param int $system
    * @param string $name
    * @param string $middleName
    * @param string $lastName
    * @param string $birthdate
    * @param string $ssn
    * @param int $genre
    * @param int $maritalStatus
    * @param string $curp
    * @param string $nationality
    * @param int $idFiscalEntity
    * @return User
    */
   public static function create($username, $password, $status, $idAccessRole, $system, $name, $middleName, $lastName, $birthdate, $ssn, $genre, $maritalStatus, $curp, $nationality, $idFiscalEntity)
   {
      throw new Exception('Factory Deprecated');
      $newUser = new User();
      $newUser
          ->setUsername($username)
          ->setPassword($password)
          ->setStatus($status)
          ->setIdAccessRole($idAccessRole)
          ->setSystem($system)
          ->setName($name)
          ->setMiddleName($middleName)
          ->setLastName($lastName)
          ->setBirthdate($birthdate)
          ->setSsn($ssn)
          ->setGenre($genre)
          ->setMaritalStatus($maritalStatus)
          ->setCurp($curp)
          ->setNationality($nationality)
          ->setIdFiscalEntity($idFiscalEntity)
      ;
      return $newUser;
   }
   
    /**
     * Método que construye un objeto User y lo rellena con la información del rowset
     * @param array $fields El arreglo que devolvió el objeto Zend_Db despues del fetch
     * @return User 
     */
    public static function createFromArray($fields)
    {
        //print_r($fields);
        $newUser = new User();
        $newUser->setIdUser($fields['id_user']);
        $newUser->setIdPerson($fields['id_person']);
        $newUser->setUsername($fields['username']);
        $newUser->setPassword($fields['password']);
        $newUser->setStatus($fields['status']);
        $newUser->setIdAccessRole($fields['id_access_role']);
        $newUser->setSystem($fields['system']);
        $newUser->setName($fields['name']);
        $newUser->setMiddleName($fields['middle_name']);
        $newUser->setLastName($fields['last_name']);
        $newUser->setBirthdate($fields['birthdate']);
        $newUser->setSsn($fields['ssn']);
        $newUser->setGenre($fields['genre']);
        $newUser->setMaritalStatus($fields['marital_status']);
        $newUser->setCurp($fields['curp']);
        $newUser->setNationality($fields['nationality']);
        $newUser->setIdFiscalEntity($fields['id_fiscal_entity']);
        //print_r($fields);
        //var_dump($newUser);
        return $newUser;
    }
   
}
