<?php
/**
 * SRP
 *
 * SRP INELECTRA
 *
 * @category   Application
 * @package    Application_Controllers
 * @copyright  Copyright (c) 2010 PCSMEXICO
 * @author     <arturo>, $LastChangedBy$
 * @version    1.0.2 SVN: $Id$
 */

/**
 * Dependences
 */
require_once "lib/controller/CrudController.php";
require_once "application/models/catalogs/ProjectLogCatalog.php";

/**
 * ProjectLogController (CRUD for the ProjectLog Objects)
 *
 * @category   Project
 * @package    Project_Controllers
 * @copyright  Copyright (c) 2010 PCSMEXICO 
 * @copyright  This File has been proudly generated by Bender (http://code.google.com/p/bender-modeler/). <chentepixtol> <zetta>
 * @author     <zetta> & <chentepixtol>
 * @version    1.0.2 SVN: $Revision$
 */
class ProjectLogController extends CrudController
{
    
    /**
     * alias for the list action
     */
    public function indexAction()
    {
        $this->_forward('list');
    }
    
    /**
     * List the objects ProjectLog actives
     */
    public function listAction()
    {
        $this->view->projectLogs = ProjectLogCatalog::getInstance()->getActives();
        $this->setTitle('List the ProjectLog');
    }
    
    /**
     * delete an ProjectLog
     */
    public function deleteAction()
    {
        $projectLogCatalog = ProjectLogCatalog::getInstance();
        $idProjectLog = $this->getRequest()->getParam('idProjectLog');
        $projectLog = $projectLogCatalog->getById($idProjectLog);
        $projectLogCatalog->deactivate($projectLog);
        $this->setFlash('ok','Successfully removed the ProjectLog');
        $this->_redirect('project-log/list');
    }
    
    /**
     * Form for edit an ProjectLog
     */
    public function editAction()
    {
        $projectLogCatalog = ProjectLogCatalog::getInstance();
        $idProjectLog = $this->getRequest()->getParam('idProjectLog');
        $projectLog = $projectLogCatalog->getById($idProjectLog);
        $post = array(
            'id_project_log' => $projectLog->getIdProjectLog(),
            'id_project' => $projectLog->getIdProject(),
            'timestamp' => $projectLog->getTimestamp(),
        );
        $this->view->post = $post;
        $this->setTitle('Edit ProjectLog');
    }
    
    /**
     * Create an ProjectLog
     */
    public function createAction()
    {   
        $projectLogCatalog = ProjectLogCatalog::getInstance();
        $idProject = utf8_decode($this->getRequest()->getParam('id_project'));
        $timestamp = utf8_decode($this->getRequest()->getParam('timestamp'));
        $projectLog = ProjectLogFactory::create($idProject, $timestamp);
        $projectLogCatalog->create($projectLog);  
        $this->view->setTpl('_row');
        $this->view->setLayoutFile(false);
        $this->view->projectLog = $projectLog;
    }
    
    /**
     * Update an ProjectLog
     */
    public function updateAction()
    {
        $projectLogCatalog = ProjectLogCatalog::getInstance();
        $idProjectLog = $this->getRequest()->getParam('idProjectLog');
        $projectLog = $projectLogCatalog->getById($idProjectLog);
        $projectLog->setIdProject($this->getRequest()->getParam('id_project'));
        $projectLog->setTimestamp($this->getRequest()->getParam('timestamp'));
        $projectLogCatalog->update($projectLog);
        $this->setFlash('ok','Successfully edited the ProjectLog');
        $this->_redirect('project-log/list');
    }
    
}
