<?php
/**
 * SRP
 *
 * SRP INELECTRA
 *
 * @category   Application
 * @package    Application_Controllers
 * @copyright  Copyright (c) 2010 PCSMEXICO
 * @author     <arturo>, $LastChangedBy$
 * @version    1.0.2 SVN: $Id$
 */

/**
 * Dependences
 */
require_once "lib/controller/CrudController.php";
require_once "application/models/catalogs/TimetableLogStatusesCatalog.php";

/**
 * TimetableLogStatusesController (CRUD for the TimetableLogStatuses Objects)
 *
 * @category   Project
 * @package    Project_Controllers
 * @copyright  Copyright (c) 2010 PCSMEXICO 
 * @copyright  This File has been proudly generated by Bender (http://code.google.com/p/bender-modeler/). <chentepixtol> <zetta>
 * @author     <zetta> & <chentepixtol>
 * @version    1.0.2 SVN: $Revision$
 */
class TimetableLogStatusesController extends CrudController
{
    
    /**
     * alias for the list action
     */
    public function indexAction()
    {
        $this->_forward('list');
    }
    
    /**
     * List the objects TimetableLogStatuses actives
     */
    public function listAction()
    {
        $this->view->timetableLogStatusess = TimetableLogStatusesCatalog::getInstance()->getActives();
        $this->setTitle('List the TimetableLogStatuses');
    }
    
    /**
     * delete an TimetableLogStatuses
     */
    public function deleteAction()
    {
        $timetableLogStatusesCatalog = TimetableLogStatusesCatalog::getInstance();
        $idTimetableLogStatus = $this->getRequest()->getParam('idTimetableLogStatus');
        $timetableLogStatuses = $timetableLogStatusesCatalog->getById($idTimetableLogStatus);
        $timetableLogStatusesCatalog->deactivate($timetableLogStatuses);
        $this->setFlash('ok','Successfully removed the TimetableLogStatuses');
        $this->_redirect('timetable-log-statuses/list');
    }
    
    /**
     * Form for edit an TimetableLogStatuses
     */
    public function editAction()
    {
        $timetableLogStatusesCatalog = TimetableLogStatusesCatalog::getInstance();
        $idTimetableLogStatus = $this->getRequest()->getParam('idTimetableLogStatus');
        $timetableLogStatuses = $timetableLogStatusesCatalog->getById($idTimetableLogStatus);
        $post = array(
            'id_timetable_log_status' => $timetableLogStatuses->getIdTimetableLogStatus(),
            'id_timetable_log' => $timetableLogStatuses->getIdTimetableLog(),
            'status' => $timetableLogStatuses->getStatus(),
            'rejected_reason' => $timetableLogStatuses->getRejectedReason(),
        );
        $this->view->post = $post;
        $this->setTitle('Edit TimetableLogStatuses');
    }
    
    /**
     * Create an TimetableLogStatuses
     */
    public function createAction()
    {   
        $timetableLogStatusesCatalog = TimetableLogStatusesCatalog::getInstance();
        $idTimetableLog = utf8_decode($this->getRequest()->getParam('id_timetable_log'));
        $status = utf8_decode($this->getRequest()->getParam('status'));
        $rejectedReason = utf8_decode($this->getRequest()->getParam('rejected_reason'));
        $timetableLogStatuses = TimetableLogStatusesFactory::create($idTimetableLog, $status, $rejectedReason);
        $timetableLogStatusesCatalog->create($timetableLogStatuses);  
        $this->view->setTpl('_row');
        $this->view->setLayoutFile(false);
        $this->view->timetableLogStatuses = $timetableLogStatuses;
    }
    
    /**
     * Update an TimetableLogStatuses
     */
    public function updateAction()
    {
        $timetableLogStatusesCatalog = TimetableLogStatusesCatalog::getInstance();
        $idTimetableLogStatus = $this->getRequest()->getParam('idTimetableLogStatus');
        $timetableLogStatuses = $timetableLogStatusesCatalog->getById($idTimetableLogStatus);
        $timetableLogStatuses->setIdTimetableLog($this->getRequest()->getParam('id_timetable_log'));
        $timetableLogStatuses->setStatus($this->getRequest()->getParam('status'));
        $timetableLogStatuses->setRejectedReason($this->getRequest()->getParam('rejected_reason'));
        $timetableLogStatusesCatalog->update($timetableLogStatuses);
        $this->setFlash('ok','Successfully edited the TimetableLogStatuses');
        $this->_redirect('timetable-log-statuses/list');
    }
    
}
