<?php
/**
 * Bender Modeler
 *
 * Our Simple Models
 *
 * @category   lib
 * @package    lib_models
 * @copyright  Copyright (c) 2008-2010 Bender Modeler (http://www.ctrl-zetta.com/#code)
 * @author     <zetta> <chentepixtol>, $LastChangedBy$
 * @version    1.0.0 SVN: $Id$
 */

/**
 * Clase AccessRole
 *
 * @category   lib
 * @package    lib_models
 * @subpackage lib_models_beans
 * @copyright  Copyright (c) 2008-2010 Bender Modeler (http://www.ctrl-zetta.com/#code) 
 * @copyright  This File as been proudly generated by Bender (http://code.google.com/p/bender-modeler/). <chentepixtol> <zetta>
 * @author     <zetta> & <chentepixtol>
 * @version    1.0.0 SVN: $Revision$
 */
class AccessRole
{
    /**
     * Constante que contiene el nombre de la tabla 
     * @static TABLENAME
     */
    const TABLENAME = "pcs_common_access_roles";
    const ID_ACCESS_ROLE = "pcs_common_access_roles.id_access_role";
    const NAME = "pcs_common_access_roles.name";
    const STATUS = "pcs_common_access_roles.status";
    const TABLENAME_ACCESS_ROLE_SECURITY_ACTION = 'pcs_common_security_actions_access_roles';
    

    /**
     * $idAccessRole 
     * 
     * @var int $idAccessRole
     */
    private $idAccessRole;
    /**
     * $name 
     * 
     * @var string $name
     */
    private $name;
    /**
     * $status 
     * 
     * @var int $status
     */
    private $status;

    /**
     * Set the idAccessRole value
     * 
     * @param int idAccessRole
     * @return AccessRole $accessRole
     */
    public function setIdAccessRole($idAccessRole)
    {
        $this->idAccessRole = $idAccessRole;
        return $this;
    }

    /**
     * Return the idAccessRole value
     * 
     * @return int
     */
    public function getIdAccessRole()
    {
        return $this->idAccessRole;
    }

    /**
     * Set the name value
     * 
     * @param string name
     * @return AccessRole $accessRole
     */
    public function setName($name)
    {
        $this->name = $name;
        return $this;
    }

    /**
     * Return the name value
     * 
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set the status value
     * 
     * @param int status
     * @return AccessRole $accessRole
     */
    public function setStatus($status)
    {
        $this->status = $status;
        return $this;
    }

    /**
     * Return the status value
     * 
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Status
     * @var Array
     */
    public static $Status = array(
        'Active' => 1,
        'Inactive' => 2,
    );
    
    /**
     * Status Labels
     * @var Array
     */
    public static $StatusLabel = array(
        1 => 'Activo',
        2 => 'Inactivo',
    );
}
