<?php
/**
 * SRP
 *
 * Sistema de Registro de Planillas
 *
 * @category   lib
 * @package    lib_models
 * @copyright  Copyright (c) 2010 PCSMEXICO
 * @author     <marlen>, $LastChangedBy$
 * @version    1.0.0 SVN: $Id$
 */

/**
 * Clase CalendarDay
 *
 * @category   lib
 * @package    lib_models
 * @subpackage lib_models_beans
 * @copyright  Copyright (c) 2010 PCSMEXICO 
 * @copyright  This File has been proudly generated by Bender (http://code.google.com/p/bender-modeler/). <chentepixtol> <zetta>
 * @author     <zetta> & <chentepixtol>
 * @version    1.0.0 SVN: $Revision$
 */
class CalendarDay
{
    /**
     * Constante que contiene el nombre de la tabla 
     * @static TABLENAME
     */
    const TABLENAME = "pcs_srp_core_calendar_days";
    const ID_DAY = "pcs_srp_core_calendar_days.id_day";
    const ID_EMPLOYEE = "pcs_srp_core_calendar_days.id_employee";
    const DAY_DATE = "pcs_srp_core_calendar_days.day_date";
    const ENABLED_DISABLED = "pcs_srp_core_calendar_days.enabled_disabled";

    /**
     * $idDay 
     * 
     * @var int $idDay
     */
    private $idDay;

    /**
     * $idEmployee 
     * 
     * @var int $idEmployee
     */
    private $idEmployee;

    /**
     * $dayDate 
     * 
     * @var string $dayDate
     */
    private $dayDate;

    /**
     * $enabledDisabled 
     * 1=>"Enable",2=>"Disabled"
     * @var int $enabledDisabled
     */
    private $enabledDisabled;

    /**
     * Set the idDay value
     * 
     * @param int idDay
     * @return CalendarDay $calendarDay
     */
    public function setIdDay($idDay)
    {
        $this->idDay = $idDay;
        return $this;
    }

    /**
     * Return the idDay value
     * 
     * @return int
     */
    public function getIdDay()
    {
        return $this->idDay;
    }

    /**
     * Set the idEmployee value
     * 
     * @param int idEmployee
     * @return CalendarDay $calendarDay
     */
    public function setIdEmployee($idEmployee)
    {
        $this->idEmployee = $idEmployee;
        return $this;
    }

    /**
     * Return the idEmployee value
     * 
     * @return int
     */
    public function getIdEmployee()
    {
        return $this->idEmployee;
    }

    /**
     * Set the dayDate value
     * 
     * @param string dayDate
     * @return CalendarDay $calendarDay
     */
    public function setDayDate($dayDate)
    {
        $this->dayDate = $dayDate;
        return $this;
    }

    /**
     * Return the dayDate value
     * 
     * @return string
     */
    public function getDayDate()
    {
        return $this->dayDate;
    }

    /**
     * Set the enabledDisabled value
     * 1=>"Enable",2=>"Disabled"
     * @param int enabledDisabled
     * @return CalendarDay $calendarDay
     */
    public function setEnabledDisabled($enabledDisabled)
    {
        $this->enabledDisabled = $enabledDisabled;
        return $this;
    }

    /**
     * Return the enabledDisabled value
     * 1=>"Enable",2=>"Disabled"
     * @return int
     */
    public function getEnabledDisabled()
    {
        return $this->enabledDisabled;
    }

}
