<?php
/**
 * SRP
 *
 * SRP INELECTRA
 *
 * @category   lib
 * @package    lib_models
 * @copyright  Copyright (c) 2010 PCSMEXICO
 * @author     <arturo>, $LastChangedBy$
 * @version    1.0.2 SVN: $Id$
 */
/**
 * Dependences
 */
require_once "application/models/beans/Project.php";

/**
 * Clase DepartmentProject
 *
 * @category   lib
 * @package    lib_models
 * @subpackage lib_models_beans
 * @copyright  Copyright (c) 2010 PCSMEXICO 
 * @copyright  This File has been proudly generated by Bender (http://code.google.com/p/bender-modeler/). <chentepixtol> <zetta>
 * @author     <zetta> & <chentepixtol>
 * @version    1.0.2 SVN: $Revision$
 */
class DepartmentProject extends Project 
{
    /**
     * Constante que contiene el nombre de la tabla 
     * @static TABLENAME
     */
    const TABLENAME = "pcs_srp_core_departments_projects";

    /**
     * Constantes para los nombres de los campos
     */
    const ID_DEPARTMENT_PROJECT = "pcs_srp_core_departments_projects.id_department_project";
    const ID_PROJECT = "pcs_srp_core_departments_projects.id_project";
    const ID_DEPARTMENT = "pcs_srp_core_departments_projects.id_department";
    

    /**
     * $idDepartmentProject 
     * 
     * @var int $idDepartmentProject
     */
    private $idDepartmentProject;
    

    /**
     * $idProject 
     * 
     * @var int $idProject
     */
    private $idProject;
    

    /**
     * $idDepartment 
     * 
     * @var int $idDepartment
     */
    private $idDepartment;

    /**
     * Set the idDepartmentProject value
     * 
     * @param int idDepartmentProject
     * @return DepartmentProject $departmentProject
     */
    public function setIdDepartmentProject($idDepartmentProject)
    {
        $this->idDepartmentProject = $idDepartmentProject;
        return $this;
    }

    /**
     * Return the idDepartmentProject value
     * 
     * @return int
     */
    public function getIdDepartmentProject()
    {
        return $this->idDepartmentProject;
    }

    /**
     * Set the idProject value
     * 
     * @param int idProject
     * @return DepartmentProject $departmentProject
     */
    public function setIdProject($idProject)
    {
        $this->idProject = $idProject;
        return $this;
    }

    /**
     * Return the idProject value
     * 
     * @return int
     */
    public function getIdProject()
    {
        return $this->idProject;
    }

    /**
     * Set the idDepartment value
     * 
     * @param int idDepartment
     * @return DepartmentProject $departmentProject
     */
    public function setIdDepartment($idDepartment)
    {
        $this->idDepartment = $idDepartment;
        return $this;
    }

    /**
     * Return the idDepartment value
     * 
     * @return int
     */
    public function getIdDepartment()
    {
        return $this->idDepartment;
    }

}
