<?php
/**
 * Bender Modeler
 *
 * Our Simple Models
 *
 * @category   lib
 * @package    lib_models
 * @copyright  Copyright (c) 2008-2010 Bender Modeler (http://www.ctrl-zetta.com/#code)
 * @author     <zetta> <chentepixtol>, $LastChangedBy$
 * @version    1.0.0 SVN: $Id$
 */

/**
 * Clase SecurityAction
 *
 * @category   lib
 * @package    lib_models
 * @subpackage lib_models_beans
 * @copyright  Copyright (c) 2008-2010 Bender Modeler (http://www.ctrl-zetta.com/#code) 
 * @copyright  This File as been proudly generated by Bender (http://code.google.com/p/bender-modeler/). <chentepixtol> <zetta>
 * @author     <zetta> & <chentepixtol>
 * @version    1.0.0 SVN: $Revision$
 */
class SecurityAction
{
    /**
     * Constante que contiene el nombre de la tabla 
     * @static TABLENAME
     */
    const TABLENAME = "pcs_common_security_actions";
    const ID_ACTION = "pcs_common_security_actions.id_action";
    const ID_CONTROLLER = "pcs_common_security_actions.id_controller";
    const NAME = "pcs_common_security_actions.name";
    const TABLENAME_SECURITY_ACTION_ACCESS_ROLE = 'pcs_common_security_actions_access_roles';

    /**
     * $idAction 
     * 
     * @var int $idAction
     */
    private $idAction;
    /**
     * $idController 
     * 
     * @var int $idController
     */
    private $idController;
    /**
     * $name 
     * 
     * @var string $name
     */
    private $name;

    /**
     * Set the idAction value
     * 
     * @param int idAction
     * @return SecurityAction $securityAction
     */
    public function setIdAction($idAction)
    {
        $this->idAction = $idAction;
        return $this;
    }

    /**
     * Return the idAction value
     * 
     * @return int
     */
    public function getIdAction()
    {
        return $this->idAction;
    }

    /**
     * Set the idController value
     * 
     * @param int idController
     * @return SecurityAction $securityAction
     */
    public function setIdController($idController)
    {
        $this->idController = $idController;
        return $this;
    }

    /**
     * Return the idController value
     * 
     * @return int
     */
    public function getIdController()
    {
        return $this->idController;
    }

    /**
     * Set the name value
     * 
     * @param string name
     * @return SecurityAction $securityAction
     */
    public function setName($name)
    {
        $this->name = $name;
        return $this;
    }

    /**
     * Return the name value
     * 
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

}
