<?php
/**
 * SRP
 *
 * SRP INELECTRA
 *
 * @category   lib
 * @package    lib_models
 * @copyright  Copyright (c) 2010 PCSMEXICO
 * @author     <arturo>, $LastChangedBy$
 * @version    1.0.2 SVN: $Id$
 */

/**
 * Clase TimetableHour
 *
 * @category   lib
 * @package    lib_models
 * @subpackage lib_models_beans
 * @copyright  Copyright (c) 2010 PCSMEXICO
 * @copyright  This File has been proudly generated by Bender (http://code.google.com/p/bender-modeler/). <chentepixtol> <zetta>
 * @author     <zetta> & <chentepixtol>
 * @version    1.0.2 SVN: $Revision$
 */
class TimetableHour
{
    /**
     * Constante que contiene el nombre de la tabla
     * @static TABLENAME
     */
    const TABLENAME = "pcs_srp_core_timetables_hours";

    /**
     * Constantes para los nombres de los campos
     */
    const ID_TIMETABLE_HOUR = "pcs_srp_core_timetables_hours.id_timetable_hour";
    const ID_TIMETABLE = "pcs_srp_core_timetables_hours.id_timetable";
    const RECORD_DATE = "pcs_srp_core_timetables_hours.record_date";
    const HOURS = "pcs_srp_core_timetables_hours.hours";
    const DATE_CREATED = "pcs_srp_core_timetables_hours.date_created";
    const TIMESTAMP = "pcs_srp_core_timetables_hours.timestamp";


    /**
     * $idTimetableHour
     *
     * @var int $idTimetableHour
     */
    private $idTimetableHour;


    /**
     * $idTimetable
     *
     * @var int $idTimetable
     */
    private $idTimetable;


    /**
     * $recordDate
     *
     * @var string $recordDate
     */
    private $recordDate;


    /**
     * $hours
     *
     * @var int $hours
     */
    private $hours;


    /**
     * $dateCreated
     *
     * @var datetime $dateCreated
     */
    private $dateCreated;


    /**
     * $timestamp
     *
     * @var string $timestamp
     */
    private $timestamp;

    /**
     * Set the idTimetableHour value
     *
     * @param int idTimetableHour
     * @return TimetableHour $timetableHour
     */
    public function setIdTimetableHour($idTimetableHour)
    {
        $this->idTimetableHour = $idTimetableHour;
        return $this;
    }

    /**
     * Return the idTimetableHour value
     *
     * @return int
     */
    public function getIdTimetableHour()
    {
        return $this->idTimetableHour;
    }

    /**
     * Set the idTimetable value
     *
     * @param int idTimetable
     * @return TimetableHour $timetableHour
     */
    public function setIdTimetable($idTimetable)
    {
        $this->idTimetable = $idTimetable;
        return $this;
    }

    /**
     * Return the idTimetable value
     *
     * @return int
     */
    public function getIdTimetable()
    {
        return $this->idTimetable;
    }

    /**
     * Set the recordDate value
     *
     * @param string recordDate
     * @return TimetableHour $timetableHour
     */
    public function setRecordDate($recordDate)
    {
        $this->recordDate = $recordDate;
        return $this;
    }

    /**
     * Return the recordDate value
     *
     * @return string
     */
    public function getRecordDate()
    {
        return $this->recordDate;
    }

    /**
     * Set the hours value
     *
     * @param int hours
     * @return TimetableHour $timetableHour
     */
    public function setHours($hours)
    {
        $this->hours = $hours;
        return $this;
    }

    /**
     * Return the hours value
     *
     * @return int
     */
    public function getHours()
    {
        return $this->hours;
    }

    /**
     * Set the dateCreated value
     *
     * @param datetime dateCreated
     * @return TimetableHour $timetableHour
     */
    public function setDateCreated($dateCreated)
    {
        $this->dateCreated = $dateCreated;
        return $this;
    }

    /**
     * Return the dateCreated value
     *
     * @return datetime
     */
    public function getDateCreated()
    {
        return $this->dateCreated;
    }

    /**
     * Set the timestamp value
     *
     * @param string timestamp
     * @return TimetableHour $timetableHour
     */
    public function setTimestamp($timestamp)
    {
        $this->timestamp = $timestamp;
        return $this;
    }

    /**
     * Return the timestamp value
     *
     * @return string
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

}
