<?php
/**
 * SRP
 *
 * SRP INELECTRA
 *
 * @category   lib
 * @package    lib_models
 * @copyright  Copyright (c) 2010 PCSMEXICO
 * @author     <arturo>, $LastChangedBy$
 * @version    1.0.2 SVN: $Id$
 */
/**
 * Dependences
 */
require_once "application/models/beans/TimetableLog.php";

/**
 * Clase TimetableLogApprover
 *
 * @category   lib
 * @package    lib_models
 * @subpackage lib_models_beans
 * @copyright  Copyright (c) 2010 PCSMEXICO 
 * @copyright  This File has been proudly generated by Bender (http://code.google.com/p/bender-modeler/). <chentepixtol> <zetta>
 * @author     <zetta> & <chentepixtol>
 * @version    1.0.2 SVN: $Revision$
 */
class TimetableLogApprover extends TimetableLog 
{
    /**
     * Constante que contiene el nombre de la tabla 
     * @static TABLENAME
     */
    const TABLENAME = "pcs_srp_core_timetables_logs_approvers";

    /**
     * Constantes para los nombres de los campos
     */
    const ID_TIMETABLE_LOG_APPROVER = "pcs_srp_core_timetables_logs_approvers.id_timetable_log_approver";
    const ID_TIMETABLE_LOG = "pcs_srp_core_timetables_logs_approvers.id_timetable_log";
    const ID_CURRENT_APPROVER = "pcs_srp_core_timetables_logs_approvers.id_current_approver";
    const ID_FORMER_APPROVER = "pcs_srp_core_timetables_logs_approvers.id_former_approver";
    

    /**
     * $idTimetableLogApprover 
     * 
     * @var int $idTimetableLogApprover
     */
    private $idTimetableLogApprover;
    

    /**
     * $idTimetableLog 
     * 
     * @var int $idTimetableLog
     */
    private $idTimetableLog;
    

    /**
     * $idCurrentApprover 
     * 
     * @var int $idCurrentApprover
     */
    private $idCurrentApprover;
    

    /**
     * $idFormerApprover 
     * 
     * @var int $idFormerApprover
     */
    private $idFormerApprover;

    /**
     * Set the idTimetableLogApprover value
     * 
     * @param int idTimetableLogApprover
     * @return TimetableLogApprover $timetableLogApprover
     */
    public function setIdTimetableLogApprover($idTimetableLogApprover)
    {
        $this->idTimetableLogApprover = $idTimetableLogApprover;
        return $this;
    }

    /**
     * Return the idTimetableLogApprover value
     * 
     * @return int
     */
    public function getIdTimetableLogApprover()
    {
        return $this->idTimetableLogApprover;
    }

    /**
     * Set the idTimetableLog value
     * 
     * @param int idTimetableLog
     * @return TimetableLogApprover $timetableLogApprover
     */
    public function setIdTimetableLog($idTimetableLog)
    {
        $this->idTimetableLog = $idTimetableLog;
        return $this;
    }

    /**
     * Return the idTimetableLog value
     * 
     * @return int
     */
    public function getIdTimetableLog()
    {
        return $this->idTimetableLog;
    }

    /**
     * Set the idCurrentApprover value
     * 
     * @param int idCurrentApprover
     * @return TimetableLogApprover $timetableLogApprover
     */
    public function setIdCurrentApprover($idCurrentApprover)
    {
        $this->idCurrentApprover = $idCurrentApprover;
        return $this;
    }

    /**
     * Return the idCurrentApprover value
     * 
     * @return int
     */
    public function getIdCurrentApprover()
    {
        return $this->idCurrentApprover;
    }

    /**
     * Set the idFormerApprover value
     * 
     * @param int idFormerApprover
     * @return TimetableLogApprover $timetableLogApprover
     */
    public function setIdFormerApprover($idFormerApprover)
    {
        $this->idFormerApprover = $idFormerApprover;
        return $this;
    }

    /**
     * Return the idFormerApprover value
     * 
     * @return int
     */
    public function getIdFormerApprover()
    {
        return $this->idFormerApprover;
    }

}
