<?php

/**
 * SRP
 *
 * SRP INELECTRA
 *
 * @category   Application
 * @package    Application_Controllers
 * @copyright  Copyright (c) 2010 PCSMEXICO
 * @author     <arturo>, $LastChangedBy$
 * @version    1.0.2 SVN: $Id$
 */
/**
 * Dependences
 */
require_once "lib/controller/CrudController.php";
require_once "application/models/catalogs/DepartmentProjectTaskCatalog.php";
require_once "lib/utils/project_task/ProjectTaskUtilities.php";
require_once "lib/managers/ProjectTaskManager.php";
define("DTASK_DIR", "./data/load/department_task/");

/**
 * DepartmentProjectTaskController (CRUD for the DepartmentProjectTask Objects)
 *
 * @category   Project
 * @package    Project_Controllers
 * @copyright  Copyright (c) 2010 PCSMEXICO 
 * @copyright  This File has been proudly generated by Bender (http://code.google.com/p/bender-modeler/). <chentepixtol> <zetta>
 * @author     <zetta> & <chentepixtol>
 * @version    1.0.2 SVN: $Revision$
 */
class DepartmentProjectTaskController extends CrudController {

    /**
     * alias for the list action
     */
    public function indexAction() {
        $this->_forward('list');
    }

    /**
     * List the objects DepartmentProjectTask actives
     */
    public function listAction() {
        $this->view->departmentProjectTasks = DepartmentProjectTaskCatalog::getInstance()->getActives();
        $this->setTitle('List the DepartmentProjectTask');
    }

    /**
     * delete an DepartmentProjectTask
     */
    public function deleteAction() {
        $departmentProjectTaskCatalog = DepartmentProjectTaskCatalog::getInstance();
        $idDepartmentProjectTask = $this->getRequest()->getParam('idDepartmentProjectTask');
        $departmentProjectTask = $departmentProjectTaskCatalog->getById($idDepartmentProjectTask);
        $departmentProjectTaskCatalog->deactivate($departmentProjectTask);
        $this->setFlash('ok', 'Successfully removed the DepartmentProjectTask');
        $this->_redirect('department-project-task/list');
    }

    /**
     * Form for edit an DepartmentProjectTask
     */
    public function editAction() {
        $departmentProjectTaskCatalog = DepartmentProjectTaskCatalog::getInstance();
        $idDepartmentProjectTask = $this->getRequest()->getParam('idDepartmentProjectTask');
        $departmentProjectTask = $departmentProjectTaskCatalog->getById($idDepartmentProjectTask);
        $post = array(
            'id_department_project_task' => $departmentProjectTask->getIdDepartmentProjectTask(),
            'id_project_task' => $departmentProjectTask->getIdProjectTask(),
        );
        $this->view->post = $post;
        $this->setTitle('Edit DepartmentProjectTask');
    }

    /**
     * Create an DepartmentProjectTask
     */
    public function createAction() {
        $departmentProjectTaskCatalog = DepartmentProjectTaskCatalog::getInstance();
        $idProjectTask = utf8_decode($this->getRequest()->getParam('id_project_task'));
        $departmentProjectTask = DepartmentProjectTaskFactory::create($idProjectTask);
        $departmentProjectTaskCatalog->create($departmentProjectTask);
        $this->view->setTpl('_row');
        $this->view->setLayoutFile(false);
        $this->view->departmentProjectTask = $departmentProjectTask;
    }

    /**
     * Update an DepartmentProjectTask
     */
    public function updateAction() {
        $departmentProjectTaskCatalog = DepartmentProjectTaskCatalog::getInstance();
        $idDepartmentProjectTask = $this->getRequest()->getParam('idDepartmentProjectTask');
        $departmentProjectTask = $departmentProjectTaskCatalog->getById($idDepartmentProjectTask);
        $departmentProjectTask->setIdProjectTask($this->getRequest()->getParam('id_project_task'));
        $departmentProjectTaskCatalog->update($departmentProjectTask);
        $this->setFlash('ok', 'Successfully edited the DepartmentProjectTask');
        $this->_redirect('department-project-task/list');
    }

    /**
     * Upload a set of Project Tasks
     */
    public function uploadAction() {
        try {
            $row = 0;
            $archives = glob(DTASK_DIR . "*.csv");
            if (count($archives) > 1)
                $this->view->warning_files = "Se encontró mas de un archivo csv";
            if (($handle = fopen($archives[0], "r")) !== FALSE) {
                while (($data = fgetcsv($handle, 1000, "|")) !== FALSE) {
                    if ($row == 0)
                        $titles = $data;
                    else
                        foreach ($data as $k => $v)
                            $data_fields[$row][$titles[$k]] = $v;
                    $row++;
                }
                fclose($handle);
                $digested_file = ProjectTaskUtilities::getInstance()->validateRowFields($data_fields);
//           print_r($digested_file);
//            die();
                foreach ($digested_file["reported_rows"] as $key => $reported_row) {
                    unset($reported_row["ERROR"]);
                    $csv_lines[$key] = implode("|", $reported_row);
                }
                $result = ProjectTaskManager::getInstance()->upload_create($digested_file["ok_rows"], "2");
                $this->view->reported_rows = $digested_file["reported_rows"];
                $this->view->reported_rows_count = count($digested_file["reported_rows"]);
                $this->view->ok_rows = $digested_file["ok_rows"];
                $this->view->ok_rows_count = count($digested_file["ok_rows"]);
                $this->view->inserted_rows = $result["inserted_rows"];
                $this->view->db_errors = $result["db_errors"];
                $this->view->db_errors_count = count($result["db_errors"]);
                $this->view->csv_lines = $csv_lines;
                $this->view->rows_count = $row - 1;
                //unlink($archives[0]);
            }
        } catch (Exception $e) {
            $this->view->warning_files = "No hay ningun archivo para carga de datos";
        }
    }

    public function getTasksAction(){
        $this->noRender();
        echo (json_encode(ProjectTaskCatalog::getInstance()->getByProject($this->getRequest()->getParam("id_project"))->toArray()));
    }
}
