<?php
/**
 * SRP
 *
 * Sistema de Registro de Planillas
 *
 * @category   lib
 * @package    lib_models
 * @copyright  Copyright (c) 2010 PCSMEXICO
 * @author     <marlen>, $LastChangedBy$
 * @version    1.0.0 SVN: $Id$
 */
/**
 * Dependences
 */
require_once "application/models/beans/CalendarDay.php";

/**
 * Clase CalendarDayFactory
 *
 * @category   lib
 * @package    lib_models
 * @subpackage lib_models_factories
 * @copyright  Copyright (c) 2010 PCSMEXICO 
 * @copyright  This File has been proudly generated by Bender (http://code.google.com/p/bender-modeler/). <chentepixtol> <zetta>
 * @author     <zetta> & <chentepixtol>
 * @version    1.0.0 SVN: $Revision$
 */
class CalendarDayFactory
{



   /**
    * Create a new CalendarDay instance
    * @param int $idEmployee
    * @param string $dayDate
    * @param int $enabledDisabled
    * @return CalendarDay
    */
   public static function create($idEmployee, $dayDate, $enabledDisabled)
   {
      $newCalendarDay = new CalendarDay();
      $newCalendarDay->setIdEmployee($idEmployee);
      $newCalendarDay->setDayDate($dayDate);
      $newCalendarDay->setEnabledDisabled($enabledDisabled);
      return $newCalendarDay;
   }
   
    /**
     * Método que construye un objeto CalendarDay y lo rellena con la información del rowset
     * @param array $fields El arreglo que devolvió el objeto Zend_Db despues del fetch
     * @return CalendarDay 
     */
    public static function createFromArray($fields)
    {
        $newCalendarDay = new CalendarDay();
        $newCalendarDay->setIdDay($fields['id_day']);
        $newCalendarDay->setIdEmployee($fields['id_employee']);
        $newCalendarDay->setDayDate($fields['day_date']);
        $newCalendarDay->setEnabledDisabled($fields['enabled_disabled']);
        return $newCalendarDay;
    }
   
}
