<?php
/**
 * SRP
 *
 * SRP INELECTRA
 *
 * @category   lib
 * @package    lib_models
 * @copyright  Copyright (c) 2010 PCSMEXICO
 * @author     <arturo>, $LastChangedBy$
 * @version    1.0.2 SVN: $Id$
 */
/**
 * Dependences
 */
require_once "application/models/beans/DepartmentProject.php";

/**
 * Clase DepartmentProjectFactory
 *
 * @category   lib
 * @package    lib_models
 * @subpackage lib_models_factories
 * @copyright  Copyright (c) 2010 PCSMEXICO 
 * @copyright  This File has been proudly generated by Bender (http://code.google.com/p/bender-modeler/). <chentepixtol> <zetta>
 * @author     <zetta> & <chentepixtol>
 * @version    1.0.2 SVN: $Revision$
 */
class DepartmentProjectFactory
{

   /**
    * Create a new DepartmentProject instance
    * @param int $idDepartment
    * @param int $type
    * @param int $status
    * @return DepartmentProject
    */
   public static function create($idDepartment, $type, $status)
   {
      //throw new Exception('Factory Deprecated');
      $newDepartmentProject = new DepartmentProject();
      $newDepartmentProject
          ->setIdDepartment($idDepartment)
          ->setType($type)
          ->setStatus($status)
      ;
      return $newDepartmentProject;
   }
   
    /**
     * Método que construye un objeto DepartmentProject y lo rellena con la información del rowset
     * @param array $fields El arreglo que devolvió el objeto Zend_Db despues del fetch
     * @return DepartmentProject 
     */
    public static function createFromArray($fields)
    {
        $newDepartmentProject = new DepartmentProject();
        $newDepartmentProject->setIdDepartmentProject($fields['id_department_project']);
        $newDepartmentProject->setIdProject($fields['id_project']);
        $newDepartmentProject->setIdDepartment($fields['id_department']);
        $newDepartmentProject->setType($fields['type']);
        $newDepartmentProject->setStatus($fields['status']);
        return $newDepartmentProject;
    }
   
}
