<?php
/**
 * SRP
 *
 * SRP INELECTRA
 *
 * @category   lib
 * @package    lib_models
 * @copyright  Copyright (c) 2010 PCSMEXICO
 * @author     <arturo>, $LastChangedBy$
 * @version    1.0.2 SVN: $Id$
 */
/**
 * Dependences
 */
require_once "application/models/beans/Person.php";

/**
 * Clase PersonFactory
 *
 * @category   lib
 * @package    lib_models
 * @subpackage lib_models_factories
 * @copyright  Copyright (c) 2010 PCSMEXICO 
 * @copyright  This File has been proudly generated by Bender (http://code.google.com/p/bender-modeler/). <chentepixtol> <zetta>
 * @author     <zetta> & <chentepixtol>
 * @version    1.0.2 SVN: $Revision$
 */
class PersonFactory
{

   /**
    * Create a new Person instance
    * @param string $name
    * @param string $middleName
    * @param string $lastName
    * @param string $birthdate
    * @param string $ssn
    * @param int $genre
    * @param int $maritalStatus
    * @param string $curp
    * @param string $nationality
    * @param int $idFiscalEntity
    * @return Person
    */
   public static function create($name, $middleName, $lastName, $birthdate, $ssn, $genre, $maritalStatus, $curp, $nationality, $idFiscalEntity)
   {
      throw new Exception('Factory Deprecated');
      $newPerson = new Person();
      $newPerson
          ->setName($name)
          ->setMiddleName($middleName)
          ->setLastName($lastName)
          ->setBirthdate($birthdate)
          ->setSsn($ssn)
          ->setGenre($genre)
          ->setMaritalStatus($maritalStatus)
          ->setCurp($curp)
          ->setNationality($nationality)
          ->setIdFiscalEntity($idFiscalEntity)
      ;
      return $newPerson;
   }
   
    /**
     * Método que construye un objeto Person y lo rellena con la información del rowset
     * @param array $fields El arreglo que devolvió el objeto Zend_Db despues del fetch
     * @return Person 
     */
    public static function createFromArray($fields)
    {
        $newPerson = new Person();
        $newPerson->setIdPerson($fields['id_person']);
        $newPerson->setName($fields['name']);
        $newPerson->setMiddleName($fields['middle_name']);
        $newPerson->setLastName($fields['last_name']);
        $newPerson->setBirthdate($fields['birthdate']);
        $newPerson->setSsn($fields['ssn']);
        $newPerson->setGenre($fields['genre']);
        $newPerson->setMaritalStatus($fields['marital_status']);
        $newPerson->setCurp($fields['curp']);
        $newPerson->setNationality($fields['nationality']);
        $newPerson->setIdFiscalEntity($fields['id_fiscal_entity']);
        return $newPerson;
    }
   
}
