<?php
/**
 * SRP
 *
 * SRP INELECTRA
 *
 * @category   lib
 * @package    lib_models
 * @copyright  Copyright (c) 2010 PCSMEXICO
 * @author     <arturo>, $LastChangedBy$
 * @version    1.0.2 SVN: $Id$
 */
/**
 * Dependences
 */
require_once "application/models/beans/Project.php";

/**
 * Clase ProjectFactory
 *
 * @category   lib
 * @package    lib_models
 * @subpackage lib_models_factories
 * @copyright  Copyright (c) 2010 PCSMEXICO 
 * @copyright  This File has been proudly generated by Bender (http://code.google.com/p/bender-modeler/). <chentepixtol> <zetta>
 * @author     <zetta> & <chentepixtol>
 * @version    1.0.2 SVN: $Revision$
 */
class ProjectFactory
{

   /**
    * Create a new Project instance
    * @param int $type
    * @param int $status
    * @return Project
    */
   public static function create($type, $status)
   {
      throw new Exception('Factory Deprecated');
      $newProject = new Project();
      $newProject
          ->setType($type)
          ->setStatus($status)
      ;
      return $newProject;
   }
   
    /**
     * Método que construye un objeto Project y lo rellena con la información del rowset
     * @param array $fields El arreglo que devolvió el objeto Zend_Db despues del fetch
     * @return Project 
     */
    public static function createFromArray($fields)
    {
        $newProject = new Project();
        $newProject->setIdProject($fields['id_project']);
        $newProject->setType($fields['type']);
        $newProject->setStatus($fields['status']);
        return $newProject;
    }
   
}
