<?php
/**
 * SRP
 *
 * SRP INELECTRA
 *
 * @category   lib
 * @package    lib_models
 * @copyright  Copyright (c) 2010 PCSMEXICO
 * @author     <arturo>, $LastChangedBy$
 * @version    1.0.2 SVN: $Id$
 */
/**
 * Dependences
 */
require_once "application/models/beans/ProjectTaskLog.php";

/**
 * Clase ProjectTaskLogFactory
 *
 * @category   lib
 * @package    lib_models
 * @subpackage lib_models_factories
 * @copyright  Copyright (c) 2010 PCSMEXICO 
 * @copyright  This File has been proudly generated by Bender (http://code.google.com/p/bender-modeler/). <chentepixtol> <zetta>
 * @author     <zetta> & <chentepixtol>
 * @version    1.0.2 SVN: $Revision$
 */
class ProjectTaskLogFactory
{

   /**
    * Create a new ProjectTaskLog instance
    * @param int $idProjectTask
    * @param string $timestamp
    * @return ProjectTaskLog
    */
   public static function create($idProjectTask, $timestamp)
   {
      throw new Exception('Factory Deprecated');
      $newProjectTaskLog = new ProjectTaskLog();
      $newProjectTaskLog
          ->setIdProjectTask($idProjectTask)
          ->setTimestamp($timestamp)
      ;
      return $newProjectTaskLog;
   }
   
    /**
     * Método que construye un objeto ProjectTaskLog y lo rellena con la información del rowset
     * @param array $fields El arreglo que devolvió el objeto Zend_Db despues del fetch
     * @return ProjectTaskLog 
     */
    public static function createFromArray($fields)
    {
        $newProjectTaskLog = new ProjectTaskLog();
        $newProjectTaskLog->setIdProjectTaskLog($fields['id_project_task_log']);
        $newProjectTaskLog->setIdProjectTask($fields['id_project_task']);
        $newProjectTaskLog->setTimestamp($fields['timestamp']);
        return $newProjectTaskLog;
    }
   
}
