<?php
/**
 * SRP
 *
 * SRP INELECTRA
 *
 * @category   lib
 * @package    lib_models
 * @copyright  Copyright (c) 2010 PCSMEXICO
 * @author     <arturo>, $LastChangedBy$
 * @version    1.0.2 SVN: $Id$
 */
/**
 * Dependences
 */
require_once "application/models/beans/SpecificProject.php";

/**
 * Clase SpecificProjectFactory
 *
 * @category   lib
 * @package    lib_models
 * @subpackage lib_models_factories
 * @copyright  Copyright (c) 2010 PCSMEXICO 
 * @copyright  This File has been proudly generated by Bender (http://code.google.com/p/bender-modeler/). <chentepixtol> <zetta>
 * @author     <zetta> & <chentepixtol>
 * @version    1.0.2 SVN: $Revision$
 */
class SpecificProjectFactory
{

   /**
    * Create a new SpecificProject instance
    * @param string $projectCode
    * @param string $projectName
    * @param datetime $beginningDate
    * @param datetime $endingDate
    * @param int $type
    * @param int $status
    * @return SpecificProject
    */
   public static function create($projectCode, $projectName, $beginningDate, $endingDate, $type, $status)
   {
      throw new Exception('Factory Deprecated');
      $newSpecificProject = new SpecificProject();
      $newSpecificProject
          ->setProjectCode($projectCode)
          ->setProjectName($projectName)
          ->setBeginningDate($beginningDate)
          ->setEndingDate($endingDate)
          ->setType($type)
          ->setStatus($status)
      ;
      return $newSpecificProject;
   }
   
    /**
     * Método que construye un objeto SpecificProject y lo rellena con la información del rowset
     * @param array $fields El arreglo que devolvió el objeto Zend_Db despues del fetch
     * @return SpecificProject 
     */
    public static function createFromArray($fields)
    {
        $newSpecificProject = new SpecificProject();
        $newSpecificProject->setIdSpecificProject($fields['id_specific_project']);
        $newSpecificProject->setIdProject($fields['id_project']);
        $newSpecificProject->setProjectCode($fields['project_code']);
        $newSpecificProject->setProjectName($fields['project_name']);
        $newSpecificProject->setBeginningDate($fields['beginning_date']);
        $newSpecificProject->setEndingDate($fields['ending_date']);
        $newSpecificProject->setType($fields['type']);
        $newSpecificProject->setStatus($fields['status']);
        return $newSpecificProject;
    }
   
}
