<?php
/**
 * SRP
 *
 * SRP INELECTRA
 *
 * @category   lib
 * @package    lib_models
 * @copyright  Copyright (c) 2010 PCSMEXICO
 * @author     <arturo>, $LastChangedBy$
 * @version    1.0.2 SVN: $Id$
 */
/**
 * Dependences
 */
require_once "application/models/beans/TimetableHour.php";

/**
 * Clase TimetableHourFactory
 *
 * @category   lib
 * @package    lib_models
 * @subpackage lib_models_factories
 * @copyright  Copyright (c) 2010 PCSMEXICO 
 * @copyright  This File has been proudly generated by Bender (http://code.google.com/p/bender-modeler/). <chentepixtol> <zetta>
 * @author     <zetta> & <chentepixtol>
 * @version    1.0.2 SVN: $Revision$
 */
class TimetableHourFactory
{

   /**
    * Create a new TimetableHour instance
    * @param int $idTimetable
    * @param int $idProjectTask
    * @param int $idProject
    * @param datetime $recordDate
    * @param string $description
    * @param int $hours
    * @param datetime $dateCreated
    * @param string $timestamp
    * @param int $status
    * @param int $type
    * @return TimetableHour
    */
   public static function create($idTimetable, $idProjectTask, $idProject, $recordDate, $description, $hours, $dateCreated, $timestamp, $status, $type)
   {
     // throw new Exception('Factory Deprecated');
      $newTimetableHour = new TimetableHour();
      $newTimetableHour
          ->setIdTimetable($idTimetable)
          ->setIdProjectTask($idProjectTask)
          ->setIdProject($idProject)
          ->setRecordDate($recordDate)
          ->setDescription($description)
          ->setHours($hours)
          ->setDateCreated($dateCreated)
          ->setTimestamp($timestamp)
          ->setStatus($status)
          ->setType($type)
      ;
      return $newTimetableHour;
   }
   
    /**
     * Método que construye un objeto TimetableHour y lo rellena con la información del rowset
     * @param array $fields El arreglo que devolvió el objeto Zend_Db despues del fetch
     * @return TimetableHour 
     */
    public static function createFromArray($fields)
    {
        $newTimetableHour = new TimetableHour();
        $newTimetableHour->setIdTimetableHour($fields['id_timetable_hour']);
        $newTimetableHour->setIdTimetable($fields['id_timetable']);
        $newTimetableHour->setIdProjectTask($fields['id_project_task']);
        $newTimetableHour->setIdProject($fields['id_project']);
        $newTimetableHour->setRecordDate($fields['record_date']);
        $newTimetableHour->setDescription($fields['description']);
        $newTimetableHour->setHours($fields['hours']);
        $newTimetableHour->setDateCreated($fields['date_created']);
        $newTimetableHour->setTimestamp($fields['timestamp']);
        $newTimetableHour->setStatus($fields['status']);
        $newTimetableHour->setType($fields['type']);
        return $newTimetableHour;
    }
   
}
