<?php
/**
 * Bender Modeler
 *
 * Our Simple Models
 *
 * @category   lib
 * @package    lib_models
 * @copyright  Copyright (c) 2008-2010 Bender Modeler (http://www.ctrl-zetta.com/#code)
 * @author     <zetta> <chentepixtol>, $LastChangedBy$
 * @version    1.0.0 SVN: $Id$
 */
/**
 * Dependences
 */
require_once "application/models/beans/UserLog.php";

/**
 * Clase UserLogFactory
 *
 * @category   lib
 * @package    lib_models
 * @subpackage lib_models_factories
 * @copyright  Copyright (c) 2008-2010 Bender Modeler (http://www.ctrl-zetta.com/#code) 
 * @copyright  This File as been proudly generated by Bender (http://code.google.com/p/bender-modeler/). <chentepixtol> <zetta>
 * @author     <zetta> & <chentepixtol>
 * @version    1.0.0 SVN: $Revision$
 */
class UserLogFactory
{

   /**
    * Create a new UserLog instance
    * @param int $idUser
    * @param int $eventType
    * @param string $ip
    * @param int $idResponsible
    * @param string $timestamp
    * @param string $note
    * @return UserLog
    */
   public static function create($idUser, $eventType, $ip, $idResponsible, $timestamp, $note)
   {
      $newUserLog = new UserLog();
      $newUserLog->setIdUser($idUser);
      $newUserLog->setEventType($eventType);
      $newUserLog->setIp($ip);
      $newUserLog->setIdResponsible($idResponsible);
      $newUserLog->setTimestamp($timestamp);
      $newUserLog->setNote($note);
      return $newUserLog;
   }
   
    /**
     * Método que construye un objeto UserLog y lo rellena con la información del rowset
     * @param array $fields El arreglo que devolvió el objeto Zend_Db despues del fetch
     * @return UserLog 
     */
    public static function createFromArray($fields)
    {
        $newUserLog = new UserLog();
        $newUserLog->setIdUserLog($fields['id_user_log']);
        $newUserLog->setIdUser($fields['id_user']);
        $newUserLog->setEventType($fields['event_type']);
        $newUserLog->setIp($fields['ip']);
        $newUserLog->setIdResponsible($fields['id_responsible']);
        $newUserLog->setTimestamp($fields['timestamp']);
        $newUserLog->setNote($fields['note']);
        return $newUserLog;
    }
   
}
