<?php
/**
 * SRP
 *
 * SRP INELECTRA
 *
 * @category   lib
 * @package    lib_models
 * @copyright  Copyright (c) 2010 PCSMEXICO
 * @author     <arturo>, $LastChangedBy$
 * @version    1.0.2 SVN: $Id$
 */

/**
 * Dependences
 */
require_once "application/models/catalogs/ProjectCatalog.php";
require_once "application/models/beans/DepartmentProject.php";
require_once "application/models/exceptions/DepartmentProjectException.php";
require_once "application/models/collections/DepartmentProjectCollection.php";
require_once "application/models/factories/DepartmentProjectFactory.php";

/**
 * Singleton DepartmentProjectCatalog Class
 *
 * @category   lib
 * @package    lib_models
 * @subpackage lib_models_catalogs
 * @copyright  Copyright (c) 2010 PCSMEXICO
 * @copyright  This File has been proudly generated by Bender (http://code.google.com/p/bender-modeler/). <chentepixtol> <zetta>
 * @author     zetta & chentepixtol
 * @version    1.0.2 SVN: $Revision$
 */
class DepartmentProjectCatalog extends ProjectCatalog
{

    /**
     * Singleton Instance
     * @var DepartmentProjectCatalog
     */
    static protected $instance = null;


    /**
     * Método para obtener la instancia del catálogo
     * @return DepartmentProjectCatalog
     */
    public static function getInstance()
    {
        if (!isset(self::$instance))
        {
          self::$instance = new self();
        }
        return self::$instance;
    }
    
    /**
     * Constructor de la clase DepartmentProjectCatalog
     * @return DepartmentProjectCatalog
     */
    protected function DepartmentProjectCatalog()
    {
        parent::ProjectCatalog();
    }

    /**
     * Metodo para agregar un DepartmentProject a la base de datos
     * @param DepartmentProject $departmentProject Objeto DepartmentProject
     */
    public function create($departmentProject)
    {
        if(!($departmentProject instanceof DepartmentProject))
            throw new DepartmentProjectException("passed parameter isn't a DepartmentProject instance");
        try
        {
            if(!$departmentProject->getIdProject())
              parent::create($departmentProject);
            $data = array(
                'id_project' => $departmentProject->getIdProject(),
                'id_department' => $departmentProject->getIdDepartment(),
            );
            $data = array_filter($data, 'Catalog::notNull');
            $this->db->insert(DepartmentProject::TABLENAME, $data);
            $departmentProject->setIdDepartmentProject($this->db->lastInsertId());
        }
        catch(Exception $e)
        {
            throw new DepartmentProjectException("The DepartmentProject can't be saved \n" . $e->getMessage());
        }
    }

    /**
     * Metodo para Obtener los datos de un objeto por su llave primaria
     * @param int $idDepartmentProject
     * @param boolean $throw
     * @return DepartmentProject|null
     */
    public function getById($idDepartmentProject, $throw = false)
    {
        try
        {
            $criteria = new Criteria();
            $criteria->add(DepartmentProject::ID_DEPARTMENT_PROJECT, $idDepartmentProject, Criteria::EQUAL);
            $newDepartmentProject = $this->getByCriteria($criteria)->getOne();
        }
        catch(Exception $e)
        {
            throw new DepartmentProjectException("Can't obtain the DepartmentProject \n" . $e->getMessage());
        }
        if($throw && null == $newDepartmentProject)
            throw new DepartmentProjectException("The DepartmentProject at $idDepartmentProject not exists ");
        return $newDepartmentProject;
    }
    
	/**
     * Metodo para Obtener los datos de un objeto por idProject
     * @param int $idProject
     * @param boolean $throw
     * @return DepartmentProject|null
     */
    public function getByIdProjectObject($idProject, $throw = false)
    {
        try
        {
            $criteria = new Criteria();
            $criteria->add(DepartmentProject::ID_PROJECT, $idProject, Criteria::EQUAL);
            $newDepartmentProject = $this->getByCriteria($criteria)->getOne();
        }
        catch(Exception $e)
        {
            throw new DepartmentProjectException("Can't obtain the DepartmentProject \n" . $e->getMessage());
        }
        if($throw && null == $newDepartmentProject)
            throw new DepartmentProjectException("The DepartmentProject at $idProject not exists ");
        return $newDepartmentProject;
    }
    
    /**
     * Metodo para Obtener una colección de objetos por varios ids
     * @param array $ids
     * @return DepartmentProjectCollection
     */
    public function getByIds(array $ids)
    {
        if(null == $ids) return new DepartmentProjectCollection();
        try
        {
            $criteria = new Criteria();
            $criteria->add(DepartmentProject::ID_DEPARTMENT_PROJECT, $ids, Criteria::IN);
            $departmentProjectCollection = $this->getByCriteria($criteria);
        }
        catch(Exception $e)
        {
            throw new DepartmentProjectException("DepartmentProjectCollection can't be populated\n" . $e->getMessage());
        }
        return $departmentProjectCollection;
    }

    /**
     * Metodo para actualizar un DepartmentProject
     * @param DepartmentProject $departmentProject 
     */
    public function update($departmentProject)
    {
        if(!($departmentProject instanceof DepartmentProject))
            throw new DepartmentProjectException("passed parameter isn't a DepartmentProject instance");
        try
        {
            $where[] = "id_department_project = '{$departmentProject->getIdDepartmentProject()}'";
            $data = array(
                'id_project' => $departmentProject->getIdProject(),
                'id_department' => $departmentProject->getIdDepartment(),
            );
            $data = array_filter($data, 'Catalog::notNull');
            $this->db->update(DepartmentProject::TABLENAME, $data, $where);
            parent::update($departmentProject);
        }
        catch(Exception $e)
        {
            throw new DepartmentProjectException("The DepartmentProject can't be updated \n" . $e->getMessage());
        }
    }
    
    /**
     * Metodo para guardar un departmentProject
     * @param DepartmentProject $departmentProject
     */	
    public function save($departmentProject)
    {
        if(!($departmentProject instanceof DepartmentProject))
            throw new DepartmentProjectException("passed parameter isn't a DepartmentProject instance");
        if(null != $departmentProject->getIdDepartmentProject())
            $this->update($departmentProject);
        else
            $this->create($departmentProject);
    }

    /**
     * Metodo para eliminar un departmentProject
     * @param DepartmentProject $departmentProject
     */
    public function delete($departmentProject)
    {
        if(!($departmentProject instanceof DepartmentProject))
            throw new DepartmentProjectException("passed parameter isn't a DepartmentProject instance");
        $this->deleteById($departmentProject->getIdDepartmentProject());
        parent::delete($departmentProject);
    }

    /**
     * Metodo para eliminar un DepartmentProject a partir de su Id
     * @param int $idDepartmentProject
     */
    public function deleteById($idDepartmentProject)
    {
        try
        {
            $where = array($this->db->quoteInto('id_department_project = ?', $idDepartmentProject));
            $this->db->delete(DepartmentProject::TABLENAME, $where);
        }
        catch(Exception $e)
        {
            throw new DepartmentProjectException("The DepartmentProject can't be deleted\n" . $e->getMessage());
        }
    }
    
    /**
     * Metodo para eliminar varios DepartmentProject a partir de su Id
     * @param array $ids
     */
    public function deleteByIds(array $ids)
    {
        try
        {
            $criteria = new Criteria();
            $criteria->add(DepartmentProject::ID_DEPARTMENT_PROJECT, $ids, Criteria::IN);
            $this->db->delete(DepartmentProject::TABLENAME, array($criteria->createSql()));
        }
        catch(Exception $e)
        {
            throw new DepartmentProjectException("Can't delete that\n" . $e->getMessage());
        }
    }
    
    /**
     * Metodo para Obtener todos los ids en un arreglo
     * @return array
     */
    public function retrieveAllIds()
    {
        return $this->getIdsByCriteria(new Criteria());
    }

    /**
     * Metodo para obtener todos los id de DepartmentProject por criterio
     * @param Criteria $criteria
     * @return array Array con todos los id de DepartmentProject que encajen en la busqueda
     */
    public function getIdsByCriteria(Criteria $criteria = null)
    {
        $criteria = (null === $criteria) ? new Criteria() : $criteria;
        return $this->getCustomFieldByCriteria(DepartmentProject::ID_DEPARTMENT_PROJECT, $criteria);
    }

    /**
     * Metodo para obtener un campo en particular de un DepartmentProject dado un criterio
     * @param string $field
     * @param Criteria $criteria
     * @param $distinct
     * @return array Array con el campo de los objetos DepartmentProject que encajen en la busqueda
     */
    public function getCustomFieldByCriteria($field, Criteria $criteria = null, $distinct = false)
    { 
        $criteria = (null === $criteria) ? new Criteria() : $criteria;
        $distinct = $distinct ? 'DISTINCT' : '';
        try
        {
            $sql = "SELECT {$distinct} {$field}
                    FROM ".DepartmentProject::TABLENAME."
                      INNER JOIN ".Project::TABLENAME." USING ( id_project )
                    WHERE  " . $criteria->createSql();
            $result = $this->db->fetchCol($sql);
        } catch(Zend_Db_Exception $e)
        {
            throw new DepartmentProjectException("No se pudieron obtener los fields de objetos DepartmentProject\n" . $e->getMessage());
        }
        return $result;
    }

    /**
     * Metodo que regresa una coleccion de objetos DepartmentProject 
     * dependiendo del criterio establecido
     * @param Criteria $criteria
     * @return DepartmentProjectCollection $departmentProjectCollection
     */
    public function getByCriteria(Criteria $criteria = null)
    {
        $criteria = (null === $criteria) ? new Criteria() : $criteria;
        $this->db->setFetchMode(Zend_Db::FETCH_ASSOC);
        try 
        {
            $sql = "SELECT * FROM ".DepartmentProject::TABLENAME."
                      INNER JOIN ".Project::TABLENAME." USING ( id_project )
                    WHERE " . $criteria->createSql();
            $departmentProjectCollection = new DepartmentProjectCollection();
            foreach ($this->db->fetchAll($sql) as $result){
                $departmentProjectCollection->append($this->getDepartmentProjectInstance($result));
            }
            //die ($sql);
        }
        catch(Zend_Db_Exception $e)
        {
            throw new DepartmentProjectException("Cant obtain DepartmentProjectCollection\n" . $e->getMessage());
        }
        return $departmentProjectCollection;
    }
    
    /**
     * Metodo que cuenta DepartmentProject 
     * dependiendo del criterio establecido
     * @param Criteria $criteria
     * @param string $field
     * @return int $count
     */
    public function countByCriteria(Criteria $criteria = null, $field = 'id_department_project')
    {
        $criteria = (null === $criteria) ? new Criteria() : $criteria;
        try 
        {
            $sql = "SELECT COUNT( $field ) FROM ".DepartmentProject::TABLENAME."
                      INNER JOIN ".Project::TABLENAME." USING ( id_project )
                    WHERE " . $criteria->createSql();   
            $count = $this->db->fetchOne($sql);
        }
        catch(Zend_Db_Exception $e)
        {
            throw new DepartmentProjectException("Cant obtain the count \n" . $e->getMessage());
        }
        return $count;
    }
    
    /**
     * Método que construye un objeto DepartmentProject y lo rellena con la información del rowset
     * @param array $result El arreglo que devolvió el objeto Zend_Db despues del fetch
     * @return DepartmentProject 
     */
    private function getDepartmentProjectInstance($result)
    {
        return DepartmentProjectFactory::createFromArray($result);
    }
  
    /**
     * Obtiene un DepartmentProjectCollection  dependiendo del idProject
     * @param int $idProject  
     * @return DepartmentProjectCollection 
     */
    public function getByIdProject($idProject)
    {
        $criteria = new Criteria();
        $criteria->add(DepartmentProject::ID_PROJECT, $idProject, Criteria::EQUAL);
        $departmentProjectCollection = $this->getByCriteria($criteria);
        return $departmentProjectCollection;
    }
  
    /**
     * Obtiene un DepartmentProjectCollection  dependiendo del idDepartment
     * @param int $idDepartment  
     * @return DepartmentProjectCollection 
     */
    public function getByIdDepartment($idDepartment)
    {
        $criteria = new Criteria();
        $criteria->add(DepartmentProject::ID_DEPARTMENT, $idDepartment, Criteria::EQUAL);
        $departmentProjectCollection = $this->getByCriteria($criteria);
        return $departmentProjectCollection;
    }


} 
 
