<?php
/**
 * SRP
 *
 * Sistema de Registro de Planillas
 *
 * @category   lib
 * @package    lib_models
 * @copyright  Copyright (c) 2010 PCSMEXICO
 * @author     <marlen>, $LastChangedBy$
 * @version    1.0.0 SVN: $Id$
 */

/**
 * Clase CalendarDayException que representa una excepcion
 *
 * @category   lib
 * @package    lib_models
 * @subpackage lib_models_exceptions
 * @copyright  Copyright (c) 2010 PCSMEXICO
 * @copyright  This File has been proudly generated by Bender (http://code.google.com/p/bender-modeler/). <chentepixtol> <zetta>
 * @author     zetta & chentepixtol
 * @version    1.0.0 SVN: $Revision$
 */
class CalendarDayException extends Exception
{

}

