<?php
/**
 * SRP
 *
 * SRP INELECTRA
 *
 * @category   lib
 * @package    lib_models
 * @copyright  Copyright (c) 2010 PCSMEXICO
 * @author     <arturo>, $LastChangedBy$
 * @version    1.0.2 SVN: $Id$
 */


require_once "lib/utils/Parser.php";

/**
 * Clase EmailCollection que representa una collección de objetos Email
 *
 * @category   lib
 * @package    lib_models
 * @subpackage lib_models_collections
 * @copyright  Copyright (c) 2010 PCSMEXICO
 * @copyright  This File has been proudly generated by Bender (http://code.google.com/p/bender-modeler/). <chentepixtol> <zetta>
 * @author     zetta & chentepixtol
 * @version    1.0.2 SVN: $Revision$
 */
class EmailCollection extends ArrayIterator
{

    /**
     * @var Parser
     */
    private $parser;
    
    /**
     * Constructor
     * @param array $array
     * @return void
     */
    public function __construct($array = array())
    {
        $this->parser = new Parser('Email');
        parent::__construct($array);
    }

    /**
     * Appends the value
     * @param Email $email
     */
    public function append($email)
    {
        parent::offsetSet($email->getIdEmail(), $email);
        $this->rewind();
    }

    /**
     * Return current array entry
     * @return Email
     */
    public function current()
    {
        return parent::current();
    }

    /**
     * Return current array entry and 
     * move to next entry
     * @return Email 
     */
    public function read()
    {
        $email = $this->current();
        $this->next();
        return $email;
    }

    /**
     * Get the first array entry
     * if exists or null if not 
     * @return Email|null 
     */
    public function getOne()
    {
        if ($this->count() > 0)
        {
            $this->seek(0);
            return $this->current();
        } else
            return null;
    }
    
    /**
     * Contains one object with $idEmail
     * @param  int $idEmail
     * @return boolean
     */
    public function contains($idEmail)
    {
        return parent::offsetExists($idEmail);
    }
    
    /**
     * Remove one object with $idEmail
     * @param  int $idEmail
     */
    public function remove($idEmail)
    {
        if( $this->contains($idEmail) )
            $this->offsetUnset($idEmail);
    }
    
    /**
     * Merge two Collections
     * @param EmailCollection $emailCollection
     * @return void
     */
    public function merge(EmailCollection $emailCollection)
    {
        $emailCollection->rewind();
        while($emailCollection->valid())
        {
            $email = $emailCollection->read();
            if( !$this->contains( $email->getIdEmail() ) )
                $this->append($email);
        }
        $emailCollection->rewind();
    }
    
    /**
     * Diff two Collections
     * @param EmailCollection $emailCollection
     * @return void
     */
    public function diff(EmailCollection $emailCollection)
    {
        $emailCollection->rewind();
        while($emailCollection->valid())
        {
            $email = $emailCollection->read();
            if( $this->contains( $email->getIdEmail() ) )
                $this->remove($email->getIdEmail());     
        }
        $emailCollection->rewind();
    }
    
    /**
     * Intersect two Collections
     * @param EmailCollection $emailCollection
     * @return EmailCollection
     */
    public function intersect(EmailCollection $emailCollection)
    {
        $newemailCollection = EmailCollection();
        $emailCollection->rewind();
        while($emailCollection->valid())
        {
            $email = $emailCollection->read();
            if( $this->contains( $email->getIdEmail() ) )
                $newemailCollection->append($email);
        }
        $emailCollection->rewind();
        return $newemailCollection;
    }
    
    /**
     * Retrieve the array with primary keys 
     * @return array
     */
    public function getPrimaryKeys()
    {
        return array_keys($this->getArrayCopy());
    }
    
    /**
     * Retrieve the Email with primary key  
     * @param  int $idEmail
     * @return Email
     */
    public function getByPK($idEmail)
    {
        return $this->contains($idEmail) ? $this[$idEmail] : null;
    }
  
    /**
     * Transforma una collection a un array
     * @return array
     */
    public function toArray()
    {
        $array = array();
        while ($this->valid())
        {
            $email = $this->read();
            $this->parser->changeBean($email);
            $array[$email->getIdEmail()] = $this->parser->toArray();
        }
        $this->rewind();
        return $array;
    }
    
    /**
     * Crea un array asociativo de $key => $value a partir de las constantes de un bean
     * @param string $ckey
     * @param string $cvalue
     * @return array
     */
    public function toKeyValueArray($ckey, $cvalue)
    {
        $array = array();
        while ($this->valid())
        {
            $email = $this->read();
            $this->parser->changeBean($email);
            $array += $this->parser->toKeyValueArray($ckey, $cvalue);
        }
        $this->rewind();
        return $array;
    }
    
    /**
     * Retrieve the parser object
     * @return Parser
     */
    public function getParser()
    {
        return $this->parser;
    }
    
    /**
     * Is Empty
     * @return boolean
     */
    public function isEmpty()
    {
        return $this->count() == 0;
    }
  
  
}

