<?php
/**
 * SRP
 *
 * SRP INELECTRA
 *
 * @category   lib
 * @package    lib_models
 * @copyright  Copyright (c) 2010 PCSMEXICO
 * @author     <arturo>, $LastChangedBy$
 * @version    1.0.2 SVN: $Id$
 */


require_once "lib/utils/Parser.php";

/**
 * Clase EmployeeCollection que representa una collección de objetos Employee
 *
 * @category   lib
 * @package    lib_models
 * @subpackage lib_models_collections
 * @copyright  Copyright (c) 2010 PCSMEXICO
 * @copyright  This File has been proudly generated by Bender (http://code.google.com/p/bender-modeler/). <chentepixtol> <zetta>
 * @author     zetta & chentepixtol
 * @version    1.0.2 SVN: $Revision$
 */
class EmployeeCollection extends ArrayIterator
{

    /**
     * @var Parser
     */
    private $parser;
    
    /**
     * Constructor
     * @param array $array
     * @return void
     */
    public function __construct($array = array())
    {
        $this->parser = new Parser('Employee');
        parent::__construct($array);
    }

    /**
     * Appends the value
     * @param Employee $employee
     */
    public function append($employee)
    {
        parent::offsetSet($employee->getIdEmployee(), $employee);
        $this->rewind();
    }

    /**
     * Return current array entry
     * @return Employee
     */
    public function current()
    {
        return parent::current();
    }

    /**
     * Return current array entry and 
     * move to next entry
     * @return Employee 
     */
    public function read()
    {
        $employee = $this->current();
        $this->next();
        return $employee;
    }

    /**
     * Get the first array entry
     * if exists or null if not 
     * @return Employee|null 
     */
    public function getOne()
    {
        if ($this->count() > 0)
        {
            $this->seek(0);
            return $this->current();
        } else
            return null;
    }
    
    /**
     * Contains one object with $idEmployee
     * @param  int $idEmployee
     * @return boolean
     */
    public function contains($idEmployee)
    {
        return parent::offsetExists($idEmployee);
    }
    
    /**
     * Remove one object with $idEmployee
     * @param  int $idEmployee
     */
    public function remove($idEmployee)
    {
        if( $this->contains($idEmployee) )
            $this->offsetUnset($idEmployee);
    }
    
    /**
     * Merge two Collections
     * @param EmployeeCollection $employeeCollection
     * @return void
     */
    public function merge(EmployeeCollection $employeeCollection)
    {
        $employeeCollection->rewind();
        while($employeeCollection->valid())
        {
            $employee = $employeeCollection->read();
            if( !$this->contains( $employee->getIdEmployee() ) )
                $this->append($employee);
        }
        $employeeCollection->rewind();
    }
    
    /**
     * Diff two Collections
     * @param EmployeeCollection $employeeCollection
     * @return void
     */
    public function diff(EmployeeCollection $employeeCollection)
    {
        $employeeCollection->rewind();
        while($employeeCollection->valid())
        {
            $employee = $employeeCollection->read();
            if( $this->contains( $employee->getIdEmployee() ) )
                $this->remove($employee->getIdEmployee());     
        }
        $employeeCollection->rewind();
    }
    
    /**
     * Intersect two Collections
     * @param EmployeeCollection $employeeCollection
     * @return EmployeeCollection
     */
    public function intersect(EmployeeCollection $employeeCollection)
    {
        $newemployeeCollection = EmployeeCollection();
        $employeeCollection->rewind();
        while($employeeCollection->valid())
        {
            $employee = $employeeCollection->read();
            if( $this->contains( $employee->getIdEmployee() ) )
                $newemployeeCollection->append($employee);
        }
        $employeeCollection->rewind();
        return $newemployeeCollection;
    }
    
    /**
     * Retrieve the array with primary keys 
     * @return array
     */
    public function getPrimaryKeys()
    {
        return array_keys($this->getArrayCopy());
    }
    
    /**
     * Retrieve the Employee with primary key  
     * @param  int $idEmployee
     * @return Employee
     */
    public function getByPK($idEmployee)
    {
        return $this->contains($idEmployee) ? $this[$idEmployee] : null;
    }
  
    /**
     * Transforma una collection a un array
     * @return array
     */
    public function toArray()
    {
        $array = array();
        while ($this->valid())
        {
            $employee = $this->read();
            $this->parser->changeBean($employee);
            $array[$employee->getIdEmployee()] = $this->parser->toArray();
        }
        $this->rewind();
        return $array;
    }
    
    /**
     * Crea un array asociativo de $key => $value a partir de las constantes de un bean
     * @param string $ckey
     * @param string $cvalue
     * @return array
     */
    public function toKeyValueArray($ckey, $cvalue)
    {
        $array = array();
        while ($this->valid())
        {
            $employee = $this->read();
            $this->parser->changeBean($employee);
            $array += $this->parser->toKeyValueArray($ckey, $cvalue);
        }
        $this->rewind();
        return $array;
    }
    
    /**
     * Retrieve the parser object
     * @return Parser
     */
    public function getParser()
    {
        return $this->parser;
    }
    
    /**
     * Is Empty
     * @return boolean
     */
    public function isEmpty()
    {
        return $this->count() == 0;
    }
  
  
}

