<?php
/**
 * SRP
 *
 * SRP INELECTRA
 *
 * @category   lib
 * @package    lib_models
 * @copyright  Copyright (c) 2010 PCSMEXICO
 * @author     <arturo>, $LastChangedBy$
 * @version    1.0.2 SVN: $Id$
 */


require_once "lib/utils/Parser.php";

/**
 * Clase ProjectApproversListCollection que representa una collección de objetos ProjectApproversList
 *
 * @category   lib
 * @package    lib_models
 * @subpackage lib_models_collections
 * @copyright  Copyright (c) 2010 PCSMEXICO
 * @copyright  This File has been proudly generated by Bender (http://code.google.com/p/bender-modeler/). <chentepixtol> <zetta>
 * @author     zetta & chentepixtol
 * @version    1.0.2 SVN: $Revision$
 */
class ProjectApproversListCollection extends ArrayIterator
{

    /**
     * @var Parser
     */
    private $parser;
    
    /**
     * Constructor
     * @param array $array
     * @return void
     */
    public function __construct($array = array())
    {
        $this->parser = new Parser('ProjectApproversList');
        parent::__construct($array);
    }

    /**
     * Appends the value
     * @param ProjectApproversList $projectApproversList
     */
    public function append($projectApproversList)
    {
        parent::offsetSet($projectApproversList->getIdProjectApproversList(), $projectApproversList);
        $this->rewind();
    }

    /**
     * Return current array entry
     * @return ProjectApproversList
     */
    public function current()
    {
        return parent::current();
    }

    /**
     * Return current array entry and 
     * move to next entry
     * @return ProjectApproversList 
     */
    public function read()
    {
        $projectApproversList = $this->current();
        $this->next();
        return $projectApproversList;
    }

    /**
     * Get the first array entry
     * if exists or null if not 
     * @return ProjectApproversList|null 
     */
    public function getOne()
    {
        if ($this->count() > 0)
        {
            $this->seek(0);
            return $this->current();
        } else
            return null;
    }
    
    /**
     * Contains one object with $idProjectApproversList
     * @param  int $idProjectApproversList
     * @return boolean
     */
    public function contains($idProjectApproversList)
    {
        return parent::offsetExists($idProjectApproversList);
    }
    
    /**
     * Remove one object with $idProjectApproversList
     * @param  int $idProjectApproversList
     */
    public function remove($idProjectApproversList)
    {
        if( $this->contains($idProjectApproversList) )
            $this->offsetUnset($idProjectApproversList);
    }
    
    /**
     * Merge two Collections
     * @param ProjectApproversListCollection $projectApproversListCollection
     * @return void
     */
    public function merge(ProjectApproversListCollection $projectApproversListCollection)
    {
        $projectApproversListCollection->rewind();
        while($projectApproversListCollection->valid())
        {
            $projectApproversList = $projectApproversListCollection->read();
            if( !$this->contains( $projectApproversList->getIdProjectApproversList() ) )
                $this->append($projectApproversList);
        }
        $projectApproversListCollection->rewind();
    }
    
    /**
     * Diff two Collections
     * @param ProjectApproversListCollection $projectApproversListCollection
     * @return void
     */
    public function diff(ProjectApproversListCollection $projectApproversListCollection)
    {
        $projectApproversListCollection->rewind();
        while($projectApproversListCollection->valid())
        {
            $projectApproversList = $projectApproversListCollection->read();
            if( $this->contains( $projectApproversList->getIdProjectApproversList() ) )
                $this->remove($projectApproversList->getIdProjectApproversList());     
        }
        $projectApproversListCollection->rewind();
    }
    
    /**
     * Intersect two Collections
     * @param ProjectApproversListCollection $projectApproversListCollection
     * @return ProjectApproversListCollection
     */
    public function intersect(ProjectApproversListCollection $projectApproversListCollection)
    {
        $newprojectApproversListCollection = ProjectApproversListCollection();
        $projectApproversListCollection->rewind();
        while($projectApproversListCollection->valid())
        {
            $projectApproversList = $projectApproversListCollection->read();
            if( $this->contains( $projectApproversList->getIdProjectApproversList() ) )
                $newprojectApproversListCollection->append($projectApproversList);
        }
        $projectApproversListCollection->rewind();
        return $newprojectApproversListCollection;
    }
    
    /**
     * Retrieve the array with primary keys 
     * @return array
     */
    public function getPrimaryKeys()
    {
        return array_keys($this->getArrayCopy());
    }
    
    /**
     * Retrieve the ProjectApproversList with primary key  
     * @param  int $idProjectApproversList
     * @return ProjectApproversList
     */
    public function getByPK($idProjectApproversList)
    {
        return $this->contains($idProjectApproversList) ? $this[$idProjectApproversList] : null;
    }
  
    /**
     * Transforma una collection a un array
     * @return array
     */
    public function toArray()
    {
        $array = array();
        while ($this->valid())
        {
            $projectApproversList = $this->read();
            $this->parser->changeBean($projectApproversList);
            $array[$projectApproversList->getIdProjectApproversList()] = $this->parser->toArray();
        }
        $this->rewind();
        return $array;
    }
    
    /**
     * Crea un array asociativo de $key => $value a partir de las constantes de un bean
     * @param string $ckey
     * @param string $cvalue
     * @return array
     */
    public function toKeyValueArray($ckey, $cvalue)
    {
        $array = array();
        while ($this->valid())
        {
            $projectApproversList = $this->read();
            $this->parser->changeBean($projectApproversList);
            $array += $this->parser->toKeyValueArray($ckey, $cvalue);
        }
        $this->rewind();
        return $array;
    }
    
    /**
     * Retrieve the parser object
     * @return Parser
     */
    public function getParser()
    {
        return $this->parser;
    }
    
    /**
     * Is Empty
     * @return boolean
     */
    public function isEmpty()
    {
        return $this->count() == 0;
    }
  
  
}

