<?php
/**
 * Bender Modeler
 *
 * Our Simple Models
 *
 * @category   lib
 * @package    lib_models
 * @copyright  Copyright (c) 2008-2010 Bender Modeler (http://www.ctrl-zetta.com/#code)
 * @author     <zetta> <chentepixtol>, $LastChangedBy$
 * @version    1.0.0 SVN: $Id$
 */


require_once "lib/utils/Parser.php";

/**
 * Clase AccessRoleCollection que representa una collección de objetos AccessRole
 *
 * @category   lib
 * @package    lib_models
 * @subpackage lib_models_collections
 * @copyright  Copyright (c) 2008-2010 Bender Modeler (http://www.ctrl-zetta.com/#code)
 * @copyright  This File as been proudly generated by Bender (http://code.google.com/p/bender-modeler/). <chentepixtol> <zetta>
 * @author     zetta & chentepixtol
 * @version    1.0.0 SVN: $Revision$
 */
class AccessRoleCollection extends ArrayIterator
{

    /**
     * @var Parser
     */
    private $parser;
    
    /**
     * Constructor
     * @param array $array
     * @return void
     */
    public function __construct($array = array())
    {
        $this->parser = new Parser('AccessRole');
        parent::__construct($array);
    }

    /**
     * Appends the value
     * @param AccessRole $accessRole
     */
    public function append(AccessRole $accessRole)
    {
        parent::offsetSet($accessRole->getIdAccessRole(), $accessRole);
        $this->rewind();
    }

    /**
     * Return current array entry
     * @return AccessRole
     */
    public function current()
    {
        return parent::current();
    }

    /**
     * Return current array entry and 
     * move to next entry
     * @return AccessRole 
     */
    public function read()
    {
        $accessRole = $this->current();
        $this->next();
        return $accessRole;
    }

    /**
     * Get the first array entry
     * if exists or null if not 
     * @return AccessRole|null 
     */
    public function getOne()
    {
        if ($this->count() > 0)
        {
            $this->seek(0);
            return $this->current();
        } else
            return null;
    }
    
    /**
     * Contains one object with $idAccessRole
     * @param  int $idAccessRole
     * @return boolean
     */
    public function contains($idAccessRole)
    {
        return parent::offsetExists($idAccessRole);
    }
    
    /**
     * Merge two Collections
     * @param AccessRoleCollection $accessRoleCollection
     * @return void
     */
    public function merge(AccessRoleCollection $accessRoleCollection)
    {
        while($accessRoleCollection->valid())
        {
            $accessRole = $accessRoleCollection->read();
            if( !$this->contains( $accessRole->getIdAccessRole() ) )
            {
                $this->append($accessRole);
            }             
        }
        $accessRoleCollection->rewind();
    }
    
    /**
     * Retrieve the array with primary keys 
     * @return array
     */
    public function getPrimaryKeys()
    {
        return array_keys($this->getArrayCopy());
    }
    
  
    /**
     * Transforma una collection a un array
     * @return array
     */
    public function toArray()
    {
        $array = array();
        while ($this->valid())
        {
            $accessRole = $this->read();
            $this->parser->changeBean($accessRole);
            $array[$accessRole->getIdAccessRole()] = $this->parser->toArray();
        }
        $this->rewind();
        return $array;
    }
    
    /**
     * Crea un array asociativo de $key => $value a partir de las constantes de un bean
     * @param string $ckey
     * @param string $cvalue
     * @return array
     */
    public function toKeyValueArray($ckey, $cvalue)
    {
        $array = array();
        while ($this->valid())
        {
            $accessRole = $this->read();
            $this->parser->changeBean($accessRole);
            $array += $this->parser->toKeyValueArray($ckey, $cvalue);
        }
        $this->rewind();
        return $array;
    }
    
    /**
     * Combo
     * @return array
     */
    public function toCombo()
    {
    	return $this->toKeyValueArray(AccessRole::ID_ACCESS_ROLE, AccessRole::NAME);
    }
    
    /**
     * Retrieve the parser object
     * @return Parser
     */
    public function getParser()
    {
        return $this->parser;
    }
  
  
}

