<?php
/**
 * SRP
 *
 * Sistema de Registro de Planillas
 *
 * @category   lib
 * @package    lib_models
 * @copyright  Copyright (c) 2010 PCSMEXICO
 * @author     <marlen>, $LastChangedBy$
 * @version    1.0.0 SVN: $Id$
 */


require_once "lib/utils/Parser.php";

/**
 * Clase CalendarDayCollection que representa una collección de objetos CalendarDay
 *
 * @category   lib
 * @package    lib_models
 * @subpackage lib_models_collections
 * @copyright  Copyright (c) 2010 PCSMEXICO
 * @copyright  This File has been proudly generated by Bender (http://code.google.com/p/bender-modeler/). <chentepixtol> <zetta>
 * @author     zetta & chentepixtol
 * @version    1.0.0 SVN: $Revision$
 */
class CalendarDayCollection extends ArrayIterator
{

    /**
     * @var Parser
     */
    private $parser;
    
    /**
     * Constructor
     * @param array $array
     * @return void
     */
    public function __construct($array = array())
    {
        $this->parser = new Parser('CalendarDay');
        parent::__construct($array);
    }

    /**
     * Appends the value
     * @param CalendarDay $calendarDay
     */
    public function append(CalendarDay $calendarDay)
    {
        parent::offsetSet($calendarDay->getIdDay(), $calendarDay);
        $this->rewind();
    }

    /**
     * Return current array entry
     * @return CalendarDay
     */
    public function current()
    {
        return parent::current();
    }

    /**
     * Return current array entry and 
     * move to next entry
     * @return CalendarDay 
     */
    public function read()
    {
        $calendarDay = $this->current();
        $this->next();
        return $calendarDay;
    }

    /**
     * Get the first array entry
     * if exists or null if not 
     * @return CalendarDay|null 
     */
    public function getOne()
    {
        if ($this->count() > 0)
        {
            $this->seek(0);
            return $this->current();
        } else
            return null;
    }
    
    /**
     * Contains one object with $idDay
     * @param  int $idDay
     * @return boolean
     */
    public function contains($idDay)
    {
        return parent::offsetExists($idDay);
    }
    
    /**
     * Merge two Collections
     * @param CalendarDayCollection $calendarDayCollection
     * @return void
     */
    public function merge(CalendarDayCollection $calendarDayCollection)
    {
        while($calendarDayCollection->valid())
        {
            $calendarDay = $calendarDayCollection->read();
            if( !$this->contains( $calendarDay->getIdDay() ) )
            {
                $this->append($calendarDay);
            }             
        }
        $calendarDayCollection->rewind();
    }
    
    /**
     * Retrieve the array with primary keys 
     * @return array
     */
    public function getPrimaryKeys()
    {
        return array_keys($this->getArrayCopy());
    }
    
    /**
     * Retrieve the CalendarDay with primary key  
     * @param  int $idDay
     * @return CalendarDay
     */
    public function getByPK($idDay)
    {
        return $this->contains($idDay) ? $this[$idDay] : null;
    }
  
    /**
     * Transforma una collection a un array
     * @return array
     */
    public function toArray()
    {
        $array = array();
        while ($this->valid())
        {
            $calendarDay = $this->read();
            $this->parser->changeBean($calendarDay);
            $array[$calendarDay->getIdDay()] = $this->parser->toArray();
        }
        $this->rewind();
        return $array;
    }
    
    /**
     * Crea un array asociativo de $key => $value a partir de las constantes de un bean
     * @param string $ckey
     * @param string $cvalue
     * @return array
     */
    public function toKeyValueArray($ckey, $cvalue)
    {
        $array = array();
        while ($this->valid())
        {
            $calendarDay = $this->read();
            $this->parser->changeBean($calendarDay);
            $array += $this->parser->toKeyValueArray($ckey, $cvalue);
        }
        $this->rewind();
        return $array;
    }
    
    /**
     * Retrieve the parser object
     * @return Parser
     */
    public function getParser()
    {
        return $this->parser;
    }
  
  
}

