<?php
/**
 * Bender Modeler
 *
 * Our Simple Models
 *
 * @category   lib
 * @package    lib_models
 * @copyright  Copyright (c) 2008-2010 Bender Modeler (http://www.ctrl-zetta.com/#code)
 * @author     <zetta> <chentepixtol>, $LastChangedBy$
 * @version    1.0.0 SVN: $Id$
 */


require_once "lib/utils/Parser.php";

/**
 * Clase MenuItemCollection que representa una collección de objetos MenuItem
 *
 * @category   lib
 * @package    lib_models
 * @subpackage lib_models_collections
 * @copyright  Copyright (c) 2008-2010 Bender Modeler (http://www.ctrl-zetta.com/#code)
 * @copyright  This File as been proudly generated by Bender (http://code.google.com/p/bender-modeler/). <chentepixtol> <zetta>
 * @author     zetta & chentepixtol
 * @version    1.0.0 SVN: $Revision$
 */
class MenuItemCollection extends ArrayIterator
{

    /**
     * @var Parser
     */
    private $parser;
    
    /**
     * Constructor
     * @param array $array
     * @return void
     */
    public function __construct($array = array())
    {
        $this->parser = new Parser('MenuItem');
        parent::__construct($array);
    }

    /**
     * Appends the value
     * @param MenuItem $menuItem
     */
    public function append(MenuItem $menuItem)
    {
        parent::offsetSet($menuItem->getIdMenuItem(), $menuItem);
        $this->rewind();
    }

    /**
     * Return current array entry
     * @return MenuItem
     */
    public function current()
    {
        return parent::current();
    }

    /**
     * Return current array entry and 
     * move to next entry
     * @return MenuItem 
     */
    public function read()
    {
        $menuItem = $this->current();
        $this->next();
        return $menuItem;
    }

    /**
     * Get the first array entry
     * if exists or null if not 
     * @return MenuItem|null 
     */
    public function getOne()
    {
        if ($this->count() > 0)
        {
            $this->seek(0);
            return $this->current();
        } else
            return null;
    }
    
    /**
     * Contains one object with $idMenuItem
     * @param  int $idMenuItem
     * @return boolean
     */
    public function contains($idMenuItem)
    {
        return parent::offsetExists($idMenuItem);
    }
    
    /**
     * Merge two Collections
     * @param MenuItemCollection $menuItemCollection
     * @return void
     */
    public function merge(MenuItemCollection $menuItemCollection)
    {
        while($menuItemCollection->valid())
        {
            $menuItem = $menuItemCollection->read();
            if( !$this->contains( $menuItem->getIdMenuItem() ) )
            {
                $this->append($menuItem);
            }             
        }
        $menuItemCollection->rewind();
    }
    
    /**
     * Retrieve the array with primary keys 
     * @return array
     */
    public function getPrimaryKeys()
    {
        return array_keys($this->getArrayCopy());
    }
    
  
    /**
     * Transforma una collection a un array
     * @return array
     */
    public function toArray()
    {
        $array = array();
        while ($this->valid())
        {
            $menuItem = $this->read();
            $this->parser->changeBean($menuItem);
            $array[$menuItem->getIdMenuItem()] = $this->parser->toArray();
        }
        $this->rewind();
        return $array;
    }
    
    /**
     * Crea un array asociativo de $key => $value a partir de las constantes de un bean
     * @param string $ckey
     * @param string $cvalue
     * @return array
     */
    public function toKeyValueArray($ckey, $cvalue)
    {
        $array = array();
        while ($this->valid())
        {
            $menuItem = $this->read();
            $this->parser->changeBean($menuItem);
            $array += $this->parser->toKeyValueArray($ckey, $cvalue);
        }
        $this->rewind();
        return $array;
    }
    
    /**
     * Retrieve the parser object
     * @return Parser
     */
    public function getParser()
    {
        return $this->parser;
    }
  
  
}

