<?php
/**
 * SRP
 *
 * SRP INELECTRA
 *
 * @category   lib
 * @package    lib_models
 * @copyright  Copyright (c) 2010 PCSMEXICO
 * @author     <arturo>, $LastChangedBy$
 * @version    1.0.2 SVN: $Id$
 */


require_once "lib/utils/Parser.php";

/**
 * Clase ProjectLogCollection que representa una collección de objetos ProjectLog
 *
 * @category   lib
 * @package    lib_models
 * @subpackage lib_models_collections
 * @copyright  Copyright (c) 2010 PCSMEXICO
 * @copyright  This File has been proudly generated by Bender (http://code.google.com/p/bender-modeler/). <chentepixtol> <zetta>
 * @author     zetta & chentepixtol
 * @version    1.0.2 SVN: $Revision$
 */
class ProjectLogCollection extends ArrayIterator
{

    /**
     * @var Parser
     */
    private $parser;
    
    /**
     * Constructor
     * @param array $array
     * @return void
     */
    public function __construct($array = array())
    {
        $this->parser = new Parser('ProjectLog');
        parent::__construct($array);
    }

    /**
     * Appends the value
     * @param ProjectLog $projectLog
     */
    public function append($projectLog)
    {
        parent::offsetSet($projectLog->getIdProjectLog(), $projectLog);
        $this->rewind();
    }

    /**
     * Return current array entry
     * @return ProjectLog
     */
    public function current()
    {
        return parent::current();
    }

    /**
     * Return current array entry and 
     * move to next entry
     * @return ProjectLog 
     */
    public function read()
    {
        $projectLog = $this->current();
        $this->next();
        return $projectLog;
    }

    /**
     * Get the first array entry
     * if exists or null if not 
     * @return ProjectLog|null 
     */
    public function getOne()
    {
        if ($this->count() > 0)
        {
            $this->seek(0);
            return $this->current();
        } else
            return null;
    }
    
    /**
     * Contains one object with $idProjectLog
     * @param  int $idProjectLog
     * @return boolean
     */
    public function contains($idProjectLog)
    {
        return parent::offsetExists($idProjectLog);
    }
    
    /**
     * Remove one object with $idProjectLog
     * @param  int $idProjectLog
     */
    public function remove($idProjectLog)
    {
        if( $this->contains($idProjectLog) )
            $this->offsetUnset($idProjectLog);
    }
    
    /**
     * Merge two Collections
     * @param ProjectLogCollection $projectLogCollection
     * @return void
     */
    public function merge(ProjectLogCollection $projectLogCollection)
    {
        $projectLogCollection->rewind();
        while($projectLogCollection->valid())
        {
            $projectLog = $projectLogCollection->read();
            if( !$this->contains( $projectLog->getIdProjectLog() ) )
                $this->append($projectLog);
        }
        $projectLogCollection->rewind();
    }
    
    /**
     * Diff two Collections
     * @param ProjectLogCollection $projectLogCollection
     * @return void
     */
    public function diff(ProjectLogCollection $projectLogCollection)
    {
        $projectLogCollection->rewind();
        while($projectLogCollection->valid())
        {
            $projectLog = $projectLogCollection->read();
            if( $this->contains( $projectLog->getIdProjectLog() ) )
                $this->remove($projectLog->getIdProjectLog());     
        }
        $projectLogCollection->rewind();
    }
    
    /**
     * Intersect two Collections
     * @param ProjectLogCollection $projectLogCollection
     * @return ProjectLogCollection
     */
    public function intersect(ProjectLogCollection $projectLogCollection)
    {
        $newprojectLogCollection = ProjectLogCollection();
        $projectLogCollection->rewind();
        while($projectLogCollection->valid())
        {
            $projectLog = $projectLogCollection->read();
            if( $this->contains( $projectLog->getIdProjectLog() ) )
                $newprojectLogCollection->append($projectLog);
        }
        $projectLogCollection->rewind();
        return $newprojectLogCollection;
    }
    
    /**
     * Retrieve the array with primary keys 
     * @return array
     */
    public function getPrimaryKeys()
    {
        return array_keys($this->getArrayCopy());
    }
    
    /**
     * Retrieve the ProjectLog with primary key  
     * @param  int $idProjectLog
     * @return ProjectLog
     */
    public function getByPK($idProjectLog)
    {
        return $this->contains($idProjectLog) ? $this[$idProjectLog] : null;
    }
  
    /**
     * Transforma una collection a un array
     * @return array
     */
    public function toArray()
    {
        $array = array();
        while ($this->valid())
        {
            $projectLog = $this->read();
            $this->parser->changeBean($projectLog);
            $array[$projectLog->getIdProjectLog()] = $this->parser->toArray();
        }
        $this->rewind();
        return $array;
    }
    
    /**
     * Crea un array asociativo de $key => $value a partir de las constantes de un bean
     * @param string $ckey
     * @param string $cvalue
     * @return array
     */
    public function toKeyValueArray($ckey, $cvalue)
    {
        $array = array();
        while ($this->valid())
        {
            $projectLog = $this->read();
            $this->parser->changeBean($projectLog);
            $array += $this->parser->toKeyValueArray($ckey, $cvalue);
        }
        $this->rewind();
        return $array;
    }
    
    /**
     * Retrieve the parser object
     * @return Parser
     */
    public function getParser()
    {
        return $this->parser;
    }
    
    /**
     * Is Empty
     * @return boolean
     */
    public function isEmpty()
    {
        return $this->count() == 0;
    }
  
  
}

