<?php
/**
 * SRP
 *
 * SRP INELECTRA
 *
 * @category   lib
 * @package    lib_models
 * @copyright  Copyright (c) 2010 PCSMEXICO
 * @author     <arturo>, $LastChangedBy$
 * @version    1.0.2 SVN: $Id$
 */


require_once "lib/utils/Parser.php";

/**
 * Clase SpecificProjectCollection que representa una collección de objetos SpecificProject
 *
 * @category   lib
 * @package    lib_models
 * @subpackage lib_models_collections
 * @copyright  Copyright (c) 2010 PCSMEXICO
 * @copyright  This File has been proudly generated by Bender (http://code.google.com/p/bender-modeler/). <chentepixtol> <zetta>
 * @author     zetta & chentepixtol
 * @version    1.0.2 SVN: $Revision$
 */
class SpecificProjectCollection extends ArrayIterator
{

    /**
     * @var Parser
     */
    private $parser;
    
    /**
     * Constructor
     * @param array $array
     * @return void
     */
    public function __construct($array = array())
    {
        $this->parser = new Parser('SpecificProject');
        parent::__construct($array);
    }

    /**
     * Appends the value
     * @param SpecificProject $specificProject
     */
    public function append($specificProject)
    {
        parent::offsetSet($specificProject->getIdSpecificProject(), $specificProject);
        $this->rewind();
    }

    /**
     * Return current array entry
     * @return SpecificProject
     */
    public function current()
    {
        return parent::current();
    }

    /**
     * Return current array entry and 
     * move to next entry
     * @return SpecificProject 
     */
    public function read()
    {
        $specificProject = $this->current();
        $this->next();
        return $specificProject;
    }

    /**
     * Get the first array entry
     * if exists or null if not 
     * @return SpecificProject|null 
     */
    public function getOne()
    {
        if ($this->count() > 0)
        {
            $this->seek(0);
            return $this->current();
        } else
            return null;
    }
    
    /**
     * Contains one object with $idSpecificProject
     * @param  int $idSpecificProject
     * @return boolean
     */
    public function contains($idSpecificProject)
    {
        return parent::offsetExists($idSpecificProject);
    }
    
    /**
     * Remove one object with $idSpecificProject
     * @param  int $idSpecificProject
     */
    public function remove($idSpecificProject)
    {
        if( $this->contains($idSpecificProject) )
            $this->offsetUnset($idSpecificProject);
    }
    
    /**
     * Merge two Collections
     * @param SpecificProjectCollection $specificProjectCollection
     * @return void
     */
    public function merge(SpecificProjectCollection $specificProjectCollection)
    {
        $specificProjectCollection->rewind();
        while($specificProjectCollection->valid())
        {
            $specificProject = $specificProjectCollection->read();
            if( !$this->contains( $specificProject->getIdSpecificProject() ) )
                $this->append($specificProject);
        }
        $specificProjectCollection->rewind();
    }
    
    /**
     * Diff two Collections
     * @param SpecificProjectCollection $specificProjectCollection
     * @return void
     */
    public function diff(SpecificProjectCollection $specificProjectCollection)
    {
        $specificProjectCollection->rewind();
        while($specificProjectCollection->valid())
        {
            $specificProject = $specificProjectCollection->read();
            if( $this->contains( $specificProject->getIdSpecificProject() ) )
                $this->remove($specificProject->getIdSpecificProject());     
        }
        $specificProjectCollection->rewind();
    }
    
    /**
     * Intersect two Collections
     * @param SpecificProjectCollection $specificProjectCollection
     * @return SpecificProjectCollection
     */
    public function intersect(SpecificProjectCollection $specificProjectCollection)
    {
        $newspecificProjectCollection = SpecificProjectCollection();
        $specificProjectCollection->rewind();
        while($specificProjectCollection->valid())
        {
            $specificProject = $specificProjectCollection->read();
            if( $this->contains( $specificProject->getIdSpecificProject() ) )
                $newspecificProjectCollection->append($specificProject);
        }
        $specificProjectCollection->rewind();
        return $newspecificProjectCollection;
    }
    
    /**
     * Retrieve the array with primary keys 
     * @return array
     */
    public function getPrimaryKeys()
    {
        return array_keys($this->getArrayCopy());
    }
    
    /**
     * Retrieve the SpecificProject with primary key  
     * @param  int $idSpecificProject
     * @return SpecificProject
     */
    public function getByPK($idSpecificProject)
    {
        return $this->contains($idSpecificProject) ? $this[$idSpecificProject] : null;
    }
  
    /**
     * Transforma una collection a un array
     * @return array
     */
    public function toArray()
    {
        $array = array();
        while ($this->valid())
        {
            $specificProject = $this->read();
            $this->parser->changeBean($specificProject);
            $array[$specificProject->getIdSpecificProject()] = $this->parser->toArray();
        }
        $this->rewind();
        return $array;
    }
    
    /**
     * Crea un array asociativo de $key => $value a partir de las constantes de un bean
     * @param string $ckey
     * @param string $cvalue
     * @return array
     */
    public function toKeyValueArray($ckey, $cvalue)
    {
        $array = array();
        while ($this->valid())
        {
            $specificProject = $this->read();
            $this->parser->changeBean($specificProject);
            $array += $this->parser->toKeyValueArray($ckey, $cvalue);
        }
        $this->rewind();
        return $array;
    }
    
    /**
     * Retrieve the parser object
     * @return Parser
     */
    public function getParser()
    {
        return $this->parser;
    }
    
    /**
     * Is Empty
     * @return boolean
     */
    public function isEmpty()
    {
        return $this->count() == 0;
    }
  
  
}

