<?php
/**
 * Bender Modeler
 *
 * Our Simple Models
 *
 * @category   lib
 * @package    lib_models
 * @copyright  Copyright (c) 2008-2010 Bender Modeler (http://www.ctrl-zetta.com/#code)
 * @author     <zetta> <chentepixtol>, $LastChangedBy$
 * @version    1.0.0 SVN: $Id$
 */

/**
 * Dependences
 */
require_once "lib/db/Catalog.php";
require_once "application/models/beans/MenuItem.php";
require_once "application/models/exceptions/MenuItemException.php";
require_once "application/models/collections/MenuItemCollection.php";
require_once "application/models/factories/MenuItemFactory.php";

/**
 * Singleton MenuItemCatalog Class
 *
 * @category   lib
 * @package    lib_models
 * @subpackage lib_models_catalogs
 * @copyright  Copyright (c) 2008-2010 Bender Modeler (http://www.ctrl-zetta.com/#code)
 * @copyright  This File as been proudly generated by Bender (http://code.google.com/p/bender-modeler/). <chentepixtol> <zetta>
 * @author     zetta & chentepixtol
 * @version    1.0.0 SVN: $Revision$
 */
class MenuItemCatalog extends Catalog
{

    /**
     * Singleton Instance
     * @var MenuItemCatalog
     */
    static protected $instance = null;


    /**
     * Método para obtener la instancia del catálogo
     * @return MenuItemCatalog
     */
    public static function getInstance()
    {
        if (!isset(self::$instance))
        {
          self::$instance = new self();
        }
        return self::$instance;
    }
    
    /**
     * Constructor de la clase MenuItemCatalog
     * @return MenuItemCatalog
     */
    protected function MenuItemCatalog()
    {
        parent::Catalog();
    }

    /**
     * Metodo para agregar un MenuItem a la base de datos
     * @param MenuItem $menuItem Objeto MenuItem
     */
    public function create($menuItem)
    {
        if(!($menuItem instanceof MenuItem))
            throw new MenuItemException("passed parameter isn't a MenuItem instance");
        try
        {
            $data = array(
                'id_action' => $menuItem->getIdAction(),
                'id_parent' => $menuItem->getIdParent(),
                'name' => $menuItem->getName(),
                'order' => $menuItem->getOrder(),
            );
            $data = array_filter($data, 'Catalog::notNull');
            $this->db->insert(MenuItem::TABLENAME, $data);
            $menuItem->setIdMenuItem($this->db->lastInsertId());
        }
        catch(Exception $e)
        {
            throw new MenuItemException("The MenuItem can't be saved \n" . $e->getMessage());
        }
    }

    /**
     * Metodo para Obtener los datos de un objeto por su llave primaria
     * @param int $idMenuItem
     * @return MenuItem|null
     */
    public function getById($idMenuItem)
    {
        try
        {
            $criteria = new Criteria();
            $criteria->add(MenuItem::ID_MENU_ITEM, $idMenuItem, Criteria::EQUAL);
            $newMenuItem = $this->getByCriteria($criteria)->getOne();
        }
        catch(Exception $e)
        {
            throw new MenuItemException("Can't obtain the MenuItem \n" . $e->getMessage());
        }
        return $newMenuItem;
    }
    
    /**
     * Metodo para Obtener una colección de objetos por varios ids
     * @param array $ids
     * @return MenuItemCollection
     */
    public function getByIds(array $ids)
    {
        if(null == $ids) return new MenuItemCollection();
        try
        {
            $criteria = new Criteria();
            $criteria->add(MenuItem::ID_MENU_ITEM, $ids, Criteria::IN);
            $menuItemCollection = $this->getByCriteria($criteria);
        }
        catch(Exception $e)
        {
            throw new MenuItemException("MenuItemCollection can't be populated\n" . $e->getMessage());
        }
        return $menuItemCollection;
    }

    /**
     * Metodo para Obtener todos los ids en un arreglo
     * @return array
     */
    public function retrieveAllIds()
    {
        try
        {
            $result = $this->db->fetchCol('SELECT id_menu_item FROM '.MenuItem::TABLENAME);
        }
        catch(Exception $e)
        {
            throw new MenuItemException("Can't obtain the ids\n" . $e->getMessage());
        }
        return $result;
    }

    /**
     * Metodo para actualizar un MenuItem
     * @param MenuItem $menuItem 
     */
    public function update($menuItem)
    {
        if(!($menuItem instanceof MenuItem))
            throw new MenuItemException("passed parameter isn't a MenuItem instance");
        try
        {
            $where[] = "id_menu_item = '{$menuItem->getIdMenuItem()}'";
            $data = array(
                'id_action' => $menuItem->getIdAction(),
                'id_parent' => $menuItem->getIdParent(),
                'name' => $menuItem->getName(),
                'order' => $menuItem->getOrder(),
            );
            $data = array_filter($data, 'Catalog::notNull');
            $this->db->update(MenuItem::TABLENAME, $data, $where);
        }
        catch(Exception $e)
        {
            throw new MenuItemException("The MenuItem can't be updated \n" . $e->getMessage());
        }
    }
    
    /**
     * Metodo para guardar un menuItem
     * @param MenuItem $menuItem
     */	
    public function save($menuItem)
    {
        if(!($menuItem instanceof MenuItem))
            throw new MenuItemException("passed parameter isn't a MenuItem instance");
        if(null != $menuItem->getIdMenuItem())
            $this->update($menuItem);
        else
            $this->create($menuItem);
    }

    /**
     * Metodo para eliminar un menuItem
     * @param MenuItem $menuItem
     */
    public function delete($menuItem)
    {
        if(!($menuItem instanceof MenuItem))
            throw new MenuItemException("passed parameter isn't a MenuItem instance");
        $this->deleteById($menuItem->getIdMenuItem());
    }

    /**
     * Metodo para eliminar un MenuItem a partir de su Id
     * @param int $idMenuItem
     */
    public function deleteById($idMenuItem)
    {
        try
        {
            $where = array($this->db->quoteInto('id_menu_item = ?', $idMenuItem));
            $this->db->delete(MenuItem::TABLENAME, $where);
        }
        catch(Exception $e)
        {
            throw new MenuItemException("The MenuItem can't be deleted\n" . $e->getMessage());
        }
    }
    
    /**
     * Metodo para eliminar varios MenuItem a partir de su Id
     * @param array $ids
     */
    public function deleteByIds(array $ids)
    {
        try
        {
            $criteria = new Criteria();
            $criteria->add(MenuItem::ID_MENU_ITEM, $ids, Criteria::IN);
            $this->db->delete(MenuItem::TABLENAME, array($criteria->createSql()));
        }
        catch(Exception $e)
        {
            throw new MenuItemException("Can't delete that\n" . $e->getMessage());
        }
    }

    /**
     * Metodo para obtener todos los id de MenuItem por criterio
     * @param Criteria $criteria
     * @return array Array con todos los id de MenuItem que encajen en la busqueda
     */
    public function getIdsByCriteria(Criteria $criteria = null)
    {
        $criteria = (null === $criteria) ? new Criteria() : $criteria;
        try
        {
            $sql = "SELECT id_menu_item
                    FROM ".MenuItem::TABLENAME."
                    WHERE  " . $criteria->createSql();
            $ids = $this->db->fetchCol($sql);
        } catch(Exception $e)
        {
            throw new MenuItemException("Can't obtain MenuItem's id\n" . $e->getMessage());
        }
        return $ids;
    }

    /**
     * Metodo para obtener un campo en particular de un MenuItem dado un criterio
     * @param string $field
     * @param Criteria $criteria
     * @return array Array con el campo de los objetos MenuItem que encajen en la busqueda
     */
    public function getCustomFieldByCriteria($field, Criteria $criteria = null)
    { 
        $criteria = (null === $criteria) ? new Criteria() : $criteria;
        try
        {
            $sql = "SELECT {$field}
                    FROM ".MenuItem::TABLENAME."
                    WHERE  " . $criteria->createSql();
            $result = $this->db->fetchCol($sql);
        } catch(Zend_Db_Exception $e)
        {
            throw new MenuItemException("No se pudieron obtener los ids de objetos {$Bean}\n" . $e->getMessage());
        }
        return $result;
    }

    /**
     * Metodo que regresa una coleccion de objetos MenuItem 
     * dependiendo del criterio establecido
     * @param Criteria $criteria
     * @return MenuItemCollection $menuItemCollection
     */
    public function getByCriteria(Criteria $criteria = null)
    {
        $criteria = (null === $criteria) ? new Criteria() : $criteria;
        $this->db->setFetchMode(Zend_Db::FETCH_ASSOC);
        try 
        {
            $sql = "SELECT * FROM ".MenuItem::TABLENAME."
                    WHERE " . $criteria->createSql();
            $menuItemCollection = new MenuItemCollection();
            foreach ($this->db->fetchAll($sql) as $result){
                $menuItemCollection->append($this->getMenuItemInstance($result));
            }
        }
        catch(Zend_Db_Exception $e)
        {
            throw new MenuItemException("Cant obtain MenuItemCollection\n" . $e->getMessage());
        }
        return $menuItemCollection;
    }
    
    /**
     * Metodo que cuenta MenuItem 
     * dependiendo del criterio establecido
     * @param Criteria $criteria
     * @param string $field
     * @return int $count
     */
    public function countByCriteria(Criteria $criteria = null, $field = 'id_menu_item')
    {
        $criteria = (null === $criteria) ? new Criteria() : $criteria;
        try 
        {
            $sql = "SELECT COUNT( $field ) FROM ".MenuItem::TABLENAME."
                    WHERE " . $criteria->createSql();   
            $count = $this->db->fetchOne($sql);
        }
        catch(Zend_Db_Exception $e)
        {
            throw new MenuItemException("Cant obtain the count \n" . $e->getMessage());
        }
        return $count;
    }
    
    /**
     * Método que construye un objeto MenuItem y lo rellena con la información del rowset
     * @param array $result El arreglo que devolvió el objeto Zend_Db despues del fetch
     * @return MenuItem 
     */
    private function getMenuItemInstance($result)
    {
        return MenuItemFactory::createFromArray($result);
    }
  
    /**
     * Obtiene un MenuItemCollection  dependiendo del idAction
     * @param int $idAction  
     * @return MenuItemCollection 
     */
    public function getByIdAction($idAction)
    {
        $criteria = new Criteria();
        $criteria->add(MenuItem::ID_ACTION, $idAction, Criteria::EQUAL);
        $menuItemCollection = $this->getByCriteria($criteria);
        return $menuItemCollection;
    }
  
    /**
     * Metodo para eliminar un MenuItem a partir de su Id
     * adem�s, borra los elementos dependientes
     * @param int $idMenuItem
     */
    public function deleteRecursiveById($idMenuItem)
    {
    	$criteria = new Criteria();
    	$criteria->add(MenuItem::ID_PARENT,$idMenuItem,Criteria::EQUAL);
    	$childs = $this->getByCriteria($criteria);
    	while ($childs->valid())
    		$this->delete($childs->read());
    	$this->deleteById($idMenuItem);
    }
    
    /**
     * Metodo que regresa una coleccion de objetos MenuItem
     * dependiendo del idParent
     * @param int $idParent
     * @param Criteria $criteria
     * @return MenuItemCollection $objects
     */
    public function getByIdParent($idParent,Criteria $criteria)
    {
      $criteria->addAscendingOrderByColumn(MenuItem::ORDER);
      if(is_null($idParent))
        $criteria->add(MenuItem::ID_PARENT,$idParent,Criteria::IS_NULL);
      else
      	$criteria->add(MenuItem::ID_PARENT,$idParent,Criteria::EQUAL);
    	return $this->getByCriteria($criteria);
    }


} 
 
