<?php
/**
 * SRP
 *
 * SRP INELECTRA
 *
 * @category   lib
 * @package    lib_models
 * @copyright  Copyright (c) 2010 PCSMEXICO
 * @author     <arturo>, $LastChangedBy$
 * @version    1.0.2 SVN: $Id$
 */

/**
 * Clase Email
 *
 * @category   lib
 * @package    lib_models
 * @subpackage lib_models_beans
 * @copyright  Copyright (c) 2010 PCSMEXICO 
 * @copyright  This File has been proudly generated by Bender (http://code.google.com/p/bender-modeler/). <chentepixtol> <zetta>
 * @author     <zetta> & <chentepixtol>
 * @version    1.0.2 SVN: $Revision$
 */
class Email
{
    /**
     * Constante que contiene el nombre de la tabla 
     * @static TABLENAME
     */
    const TABLENAME = "pcs_common_persons_emails";

    /**
     * Constantes para los nombres de los campos
     */
    const ID_EMAIL = "pcs_common_persons_emails.id_email";
    const ID_PERSON = "pcs_common_persons_emails.id_person";
    const EMAIL = "pcs_common_persons_emails.email";
    const TYPE = "pcs_common_persons_emails.type";
    

    /**
     * $idEmail 
     * 
     * @var int $idEmail
     */
    private $idEmail;
    

    /**
     * $idPerson 
     * 
     * @var int $idPerson
     */
    private $idPerson;
    

    /**
     * $email 
     * 
     * @var string $email
     */
    private $email;
    

    /**
     * $type 
     * 
     * @var int $type
     */
    private $type;

    /**
     * Set the idEmail value
     * 
     * @param int idEmail
     * @return Email $email
     */
    public function setIdEmail($idEmail)
    {
        $this->idEmail = $idEmail;
        return $this;
    }

    /**
     * Return the idEmail value
     * 
     * @return int
     */
    public function getIdEmail()
    {
        return $this->idEmail;
    }

    /**
     * Set the idPerson value
     * 
     * @param int idPerson
     * @return Email $email
     */
    public function setIdPerson($idPerson)
    {
        $this->idPerson = $idPerson;
        return $this;
    }

    /**
     * Return the idPerson value
     * 
     * @return int
     */
    public function getIdPerson()
    {
        return $this->idPerson;
    }

    /**
     * Set the email value
     * 
     * @param string email
     * @return Email $email
     */
    public function setEmail($email)
    {
        $this->email = $email;
        return $this;
    }

    /**
     * Return the email value
     * 
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Set the type value
     * 
     * @param int type
     * @return Email $email
     */
    public function setType($type)
    {
        $this->type = $type;
        return $this;
    }

    /**
     * Return the type value
     * 
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

}
