<?php
/**
 * SRP
 *
 * SRP INELECTRA
 *
 * @category   lib
 * @package    lib_models
 * @copyright  Copyright (c) 2010 PCSMEXICO
 * @author     <arturo>, $LastChangedBy$
 * @version    1.0.2 SVN: $Id$
 */

/**
 * Clase ProjectTaskLog
 *
 * @category   lib
 * @package    lib_models
 * @subpackage lib_models_beans
 * @copyright  Copyright (c) 2010 PCSMEXICO 
 * @copyright  This File has been proudly generated by Bender (http://code.google.com/p/bender-modeler/). <chentepixtol> <zetta>
 * @author     <zetta> & <chentepixtol>
 * @version    1.0.2 SVN: $Revision$
 */
class ProjectTaskLog
{
    /**
     * Constante que contiene el nombre de la tabla 
     * @static TABLENAME
     */
    const TABLENAME = "pcs_srp_core_projects_tasks_logs";

    /**
     * Constantes para los nombres de los campos
     */
    const ID_PROJECT_TASK_LOG = "pcs_srp_core_projects_tasks_logs.id_project_task_log";
    const ID_PROJECT_TASK = "pcs_srp_core_projects_tasks_logs.id_project_task";
    const TIMESTAMP = "pcs_srp_core_projects_tasks_logs.timestamp";
    

    /**
     * $idProjectTaskLog 
     * 
     * @var int $idProjectTaskLog
     */
    private $idProjectTaskLog;
    

    /**
     * $idProjectTask 
     * 
     * @var int $idProjectTask
     */
    private $idProjectTask;
    

    /**
     * $timestamp 
     * 
     * @var string $timestamp
     */
    private $timestamp;

    /**
     * Set the idProjectTaskLog value
     * 
     * @param int idProjectTaskLog
     * @return ProjectTaskLog $projectTaskLog
     */
    public function setIdProjectTaskLog($idProjectTaskLog)
    {
        $this->idProjectTaskLog = $idProjectTaskLog;
        return $this;
    }

    /**
     * Return the idProjectTaskLog value
     * 
     * @return int
     */
    public function getIdProjectTaskLog()
    {
        return $this->idProjectTaskLog;
    }

    /**
     * Set the idProjectTask value
     * 
     * @param int idProjectTask
     * @return ProjectTaskLog $projectTaskLog
     */
    public function setIdProjectTask($idProjectTask)
    {
        $this->idProjectTask = $idProjectTask;
        return $this;
    }

    /**
     * Return the idProjectTask value
     * 
     * @return int
     */
    public function getIdProjectTask()
    {
        return $this->idProjectTask;
    }

    /**
     * Set the timestamp value
     * 
     * @param string timestamp
     * @return ProjectTaskLog $projectTaskLog
     */
    public function setTimestamp($timestamp)
    {
        $this->timestamp = $timestamp;
        return $this;
    }

    /**
     * Return the timestamp value
     * 
     * @return string
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

}
