<?php
/**
 * SRP
 *
 * SRP INELECTRA
 *
 * @category   lib
 * @package    lib_models
 * @copyright  Copyright (c) 2010 PCSMEXICO
 * @author     <arturo>, $LastChangedBy$
 * @version    1.0.2 SVN: $Id$
 */
/**
 * Dependences
 */
require_once "application/models/beans/ProjectTask.php";

/**
 * Clase SpecificProjectTask
 *
 * @category   lib
 * @package    lib_models
 * @subpackage lib_models_beans
 * @copyright  Copyright (c) 2010 PCSMEXICO 
 * @copyright  This File has been proudly generated by Bender (http://code.google.com/p/bender-modeler/). <chentepixtol> <zetta>
 * @author     <zetta> & <chentepixtol>
 * @version    1.0.2 SVN: $Revision$
 */
class SpecificProjectTask extends ProjectTask 
{
    /**
     * Constante que contiene el nombre de la tabla 
     * @static TABLENAME
     */
    const TABLENAME = "pcs_srp_core_specifics_projects_tasks";

    /**
     * Constantes para los nombres de los campos
     */
    const ID_SPECIFIC_PROJECT_TASK = "pcs_srp_core_specifics_projects_tasks.id_specific_project_task";
    const ID_PROJECT_TASK = "pcs_srp_core_specifics_projects_tasks.id_project_task";
    const WORK_AUTHORIZATION_STATUS = "pcs_srp_core_specifics_projects_tasks.work_authorization_status";
    

    /**
     * $idSpecificProjectTask 
     * 
     * @var int $idSpecificProjectTask
     */
    private $idSpecificProjectTask;
    

    /**
     * $idProjectTask 
     * 
     * @var int $idProjectTask
     */
    private $idProjectTask;
    

    /**
     * $workAuthorizationStatus 
     * 
     * @var int $workAuthorizationStatus
     */
    private $workAuthorizationStatus;

    /**
     * Set the idSpecificProjectTask value
     * 
     * @param int idSpecificProjectTask
     * @return SpecificProjectTask $specificProjectTask
     */
    public function setIdSpecificProjectTask($idSpecificProjectTask)
    {
        $this->idSpecificProjectTask = $idSpecificProjectTask;
        return $this;
    }

    /**
     * Return the idSpecificProjectTask value
     * 
     * @return int
     */
    public function getIdSpecificProjectTask()
    {
        return $this->idSpecificProjectTask;
    }

    /**
     * Set the idProjectTask value
     * 
     * @param int idProjectTask
     * @return SpecificProjectTask $specificProjectTask
     */
    public function setIdProjectTask($idProjectTask)
    {
        $this->idProjectTask = $idProjectTask;
        return $this;
    }

    /**
     * Return the idProjectTask value
     * 
     * @return int
     */
    public function getIdProjectTask()
    {
        return $this->idProjectTask;
    }

    /**
     * Set the workAuthorizationStatus value
     * 
     * @param int workAuthorizationStatus
     * @return SpecificProjectTask $specificProjectTask
     */
    public function setWorkAuthorizationStatus($workAuthorizationStatus)
    {
        $this->workAuthorizationStatus = $workAuthorizationStatus;
        return $this;
    }

    /**
     * Return the workAuthorizationStatus value
     * 
     * @return int
     */
    public function getWorkAuthorizationStatus()
    {
        return $this->workAuthorizationStatus;
    }

    /**
     * WorkAuthorizationStatus
     * @var Array
     */
    public static $WorkAuthorizationStatus = array(
        'Active' => 1,
        'Inactive' => 2,
    );
    
    /**
     * WorkAuthorizationStatus Labels
     * @var Array
     */
    public static $WorkAuthorizationStatusLabel = array(
        1 => 'Activo',
        2 => 'Inactivo',
    );
}
