<?php
/**
 * SRP
 *
 * SRP INELECTRA
 *
 * @category   lib
 * @package    lib_models
 * @copyright  Copyright (c) 2010 PCSMEXICO
 * @author     <arturo>, $LastChangedBy$
 * @version    1.0.2 SVN: $Id$
 */

/**
 * Clase TimetableLog
 *
 * @category   lib
 * @package    lib_models
 * @subpackage lib_models_beans
 * @copyright  Copyright (c) 2010 PCSMEXICO 
 * @copyright  This File has been proudly generated by Bender (http://code.google.com/p/bender-modeler/). <chentepixtol> <zetta>
 * @author     <zetta> & <chentepixtol>
 * @version    1.0.2 SVN: $Revision$
 */
class TimetableLog
{
    /**
     * Constante que contiene el nombre de la tabla 
     * @static TABLENAME
     */
    const TABLENAME = "pcs_srp_core_timetables_logs";

    /**
     * Constantes para los nombres de los campos
     */
    const ID_TIMETABLE_LOG = "pcs_srp_core_timetables_logs.id_timetable_log";
    const ID_TIMETABLE = "pcs_srp_core_timetables_logs.id_timetable";
    const TIMESTAMP = "pcs_srp_core_timetables_logs.timestamp";
    const ID_EMPLOYEE = "pcs_srp_core_timetables_logs.id_employee";
    const TYPE = "pcs_srp_core_timetables_logs.type";
    

    /**
     * $idTimetableLog 
     * 
     * @var int $idTimetableLog
     */
    private $idTimetableLog;
    

    /**
     * $idTimetable 
     * 
     * @var int $idTimetable
     */
    private $idTimetable;
    

    /**
     * $timestamp 
     * 
     * @var string $timestamp
     */
    private $timestamp;
    

    /**
     * $idEmployee 
     * 
     * @var int $idEmployee
     */
    private $idEmployee;
    

    /**
     * $type 
     * 1=>approver,
2=>status,
3=>hour

     * @var int $type
     */
    private $type;

    /**
     * Set the idTimetableLog value
     * 
     * @param int idTimetableLog
     * @return TimetableLog $timetableLog
     */
    public function setIdTimetableLog($idTimetableLog)
    {
        $this->idTimetableLog = $idTimetableLog;
        return $this;
    }

    /**
     * Return the idTimetableLog value
     * 
     * @return int
     */
    public function getIdTimetableLog()
    {
        return $this->idTimetableLog;
    }

    /**
     * Set the idTimetable value
     * 
     * @param int idTimetable
     * @return TimetableLog $timetableLog
     */
    public function setIdTimetable($idTimetable)
    {
        $this->idTimetable = $idTimetable;
        return $this;
    }

    /**
     * Return the idTimetable value
     * 
     * @return int
     */
    public function getIdTimetable()
    {
        return $this->idTimetable;
    }

    /**
     * Set the timestamp value
     * 
     * @param string timestamp
     * @return TimetableLog $timetableLog
     */
    public function setTimestamp($timestamp)
    {
        $this->timestamp = $timestamp;
        return $this;
    }

    /**
     * Return the timestamp value
     * 
     * @return string
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * Set the idEmployee value
     * 
     * @param int idEmployee
     * @return TimetableLog $timetableLog
     */
    public function setIdEmployee($idEmployee)
    {
        $this->idEmployee = $idEmployee;
        return $this;
    }

    /**
     * Return the idEmployee value
     * 
     * @return int
     */
    public function getIdEmployee()
    {
        return $this->idEmployee;
    }

    /**
     * Set the type value
     * 1=>approver,
2=>status,
3=>hour

     * @param int type
     * @return TimetableLog $timetableLog
     */
    public function setType($type)
    {
        $this->type = $type;
        return $this;
    }

    /**
     * Return the type value
     * 1=>approver,
2=>status,
3=>hour

     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

}
