<?php
/**
 * SRP
 *
 * SRP INELECTRA
 *
 * @category   lib
 * @package    lib_models
 * @copyright  Copyright (c) 2010 PCSMEXICO
 * @author     <arturo>, $LastChangedBy$
 * @version    1.0.2 SVN: $Id$
 */
/**
 * Dependences
 */
require_once "application/models/beans/TimetableLog.php";

/**
 * Clase TimetableLogStatuses
 *
 * @category   lib
 * @package    lib_models
 * @subpackage lib_models_beans
 * @copyright  Copyright (c) 2010 PCSMEXICO 
 * @copyright  This File has been proudly generated by Bender (http://code.google.com/p/bender-modeler/). <chentepixtol> <zetta>
 * @author     <zetta> & <chentepixtol>
 * @version    1.0.2 SVN: $Revision$
 */
class TimetableLogStatuses extends TimetableLog 
{
    /**
     * Constante que contiene el nombre de la tabla 
     * @static TABLENAME
     */
    const TABLENAME = "pcs_srp_core_timetables_logs_statuses";

    /**
     * Constantes para los nombres de los campos
     */
    const ID_TIMETABLE_LOG_STATUS = "pcs_srp_core_timetables_logs_statuses.id_timetable_log_status";
    const ID_TIMETABLE_LOG = "pcs_srp_core_timetables_logs_statuses.id_timetable_log";
    const STATUS = "pcs_srp_core_timetables_logs_statuses.status";
    

    /**
     * $idTimetableLogStatus 
     * 
     * @var int $idTimetableLogStatus
     */
    private $idTimetableLogStatus;
    

    /**
     * $idTimetableLog 
     * 
     * @var int $idTimetableLog
     */
    private $idTimetableLog;
    

    /**
     * $status 
     * 1=>draft,
2=>released,
3=>rejected,
4=>approved,
5=>not_registered
     * @var int $status
     */
    private $status;

    /**
     * Set the idTimetableLogStatus value
     * 
     * @param int idTimetableLogStatus
     * @return TimetableLogStatuses $timetableLogStatuses
     */
    public function setIdTimetableLogStatus($idTimetableLogStatus)
    {
        $this->idTimetableLogStatus = $idTimetableLogStatus;
        return $this;
    }

    /**
     * Return the idTimetableLogStatus value
     * 
     * @return int
     */
    public function getIdTimetableLogStatus()
    {
        return $this->idTimetableLogStatus;
    }

    /**
     * Set the idTimetableLog value
     * 
     * @param int idTimetableLog
     * @return TimetableLogStatuses $timetableLogStatuses
     */
    public function setIdTimetableLog($idTimetableLog)
    {
        $this->idTimetableLog = $idTimetableLog;
        return $this;
    }

    /**
     * Return the idTimetableLog value
     * 
     * @return int
     */
    public function getIdTimetableLog()
    {
        return $this->idTimetableLog;
    }

    /**
     * Set the status value
     * 1=>draft,
2=>released,
3=>rejected,
4=>approved,
5=>not_registered
     * @param int status
     * @return TimetableLogStatuses $timetableLogStatuses
     */
    public function setStatus($status)
    {
        $this->status = $status;
        return $this;
    }

    /**
     * Return the status value
     * 1=>draft,
2=>released,
3=>rejected,
4=>approved,
5=>not_registered
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * IdTimetableLogStatus
     * @var Array
     */
    public static $IdTimetableLogStatus = array(
        'Active' => 1,
        'Inactive' => 2,
    );
    
    /**
     * IdTimetableLogStatus Labels
     * @var Array
     */
    public static $IdTimetableLogStatusLabel = array(
        1 => 'Activo',
        2 => 'Inactivo',
    );
}
